### PR TITLE
Entity search by ID in console

### LINKED ISSUE #1654: End Device Search
#### Summary
Search functionality in Console by DevEUI, DevID or Name, more fields could be added. 

#### Why do we need this?
Looking up device status to debug/monitor gets harder as the number of devices deployed reaches hundreds or thousands. Most organizations would follow a naming convention for the Device ID/Name and having the Search feature eases the management. 

#### What is already there? What do you see now?
No Search functionality available currently.

#### What is missing? What do you want to see?
A Search UI on the Applications page with the following fields

- Device ID
- Device Name
- Dev EUI
- and more if suggested by other users.

#### Environment
Console

#### How do you propose to implement this?
Implement a Search Header Section on **Applications** page.

#### Can you do this yourself and submit a Pull Request?
No

### LINKED ISSUE #1802: Add search functionality for entities in console
#### Summary
The console should enable users to search for entities by id.

Comprises #1654 

#### Why do we need this?
Better UX for users with large quantities of entities.

#### What is already there? What do you see now?
- Search endpoints in the entitiy registry
- Logic for search in our redux logics
- `searchable` flag in the `<FetchTable />`, enabling search (provided that the get action supports search queries)

#### What is missing? What do you want to see?
Wiring to (re-)enable search for entities.

#### Environment
Console

#### How do you propose to implement this?
Straightforward. A lot of logic to enable search is already there. Only thing missing is some respective wiring.

#### Can you do this yourself and submit a Pull Request?
Yes.

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Closes #1802 
Closes #1654 

image

#### Changes
- Extend SDK services to include search endpoints
- Update redux logics to enable search
- Update containers to include search

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by kschiffer** [comment]
Good catch. See https://github.com/TheThingsNetwork/lorawan-stack/issues/1814

**Comment by bafonins** [comment]
Experiencing the same issue as mentioned in https://github.com/TheThingsNetwork/lorawan-stack/pull/1803#pullrequestreview-339144615

**Comment by kschiffer** [comment]
Still blocked by #1814. The PR for that one was a false positive.

**Comment by kschiffer** [comment]
The issue has now been resolved and the branch is rebased. Please review again @bafonins

**Comment by kschiffer** [comment]
I agree with you. This needs to be fixed and we'll indeed have to change the way we handle search results in the store. I suggest merging this as it is for now and I'll open an issue.

**Comment by kschiffer** [comment]
https://github.com/TheThingsNetwork/lorawan-stack/issues/1910

**Pull request merged**
