### PR TITLE
Make device naming in protos consistent

### LINKED ISSUE #185: Inconsistent device naming in protos
**Summary:** 
At the moment, we vary between [`device`](https://github.com/TheThingsNetwork/lorawan-stack/blob/a13f534e1a52299c221c6abf53bff40d10f375b1/api/end_device.proto#L440) and [`end_device`](https://github.com/TheThingsNetwork/lorawan-stack/blob/a13f534e1a52299c221c6abf53bff40d10f375b1/api/end_device.proto#L418)
This should be properly streamlined into `end_device`.
See #170 

**What do you see now?**
Usage of `device` and `end_device` as entity name in protos.

**What do you want to see instead?**
Usage of just `end_device`.

**What can you do yourself and what do you need help with?**
I need someone with more backend experience than me to verify that I replaced all occurrences correctly.

### PR DESCRIPTION
**Pull request by kschiffer**
**Summary:**
Closes #185.
At the moment, we vary between [`device`](https://github.com/TheThingsNetwork/lorawan-stack/blob/a13f534e1a52299c221c6abf53bff40d10f375b1/api/end_device.proto#L440) and [`end_device`](https://github.com/TheThingsNetwork/lorawan-stack/blob/a13f534e1a52299c221c6abf53bff40d10f375b1/api/end_device.proto#L418)
Unless there is some reasoning behind this that I am missing, I propose to streamline the naming towards `end_device`, as this can otherwise easily be overlooked - [as has happened to me](#163 ) - especially due to the resulting difference of the otherwise similar create and update requests.

**Changes:**
- Change the property name for devices in the protos to `end_device`
- Replace all occurrences of `Device` in `SetEndDeviceRequest`'s with `EndDevice`

**Notes for Reviewers:**
I set this as draft PR, as I am not confident about the implications and whether I miss other changes that would need to be made as a result of changing the protos.

**Release Notes: _(optional)_**
- Occurrences of `device` property names inside end device protocol buffers were replaced with `end_device`

### CODE REVIEW

**Comment by htdvisser** [comment]
This change does break the existing API, but only the JSON of `SetEndDeviceRequest`s. Compared to @rvolosatovs's changes in #101 this is a pretty small one, so if we accept #101, then this one should be fine too.

cc: @johanstokking

**Comment by htdvisser** [comment]
I think you still need to run `make protos.clean protos`. Also I'm pretty sure that there are indeed more places where `Device` needs to be replaced.

**Comment by rvolosatovs** [comment]
Looks like the field name is consistent in this branch:
```
$ grep -C 3 -E '[[:space:]]+EndDevice[[:space:]]+[[:alnum:]_]+[[:space:]]*=[[:space:]]*[0-9]+.*' api/*.proto
api/end_device.proto-}
api/end_device.proto-
api/end_device.proto-message EndDevices {
api/end_device.proto:  repeated EndDevice end_devices = 1;
api/end_device.proto-}
api/end_device.proto-
api/end_device.proto-message CreateEndDeviceRequest {
api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false];
api/end_device.proto-}
api/end_device.proto-
api/end_device.proto-message UpdateEndDeviceRequest {
api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false];
api/end_device.proto-  google.protobuf.FieldMask field_mask = 2 [(gogoproto.nullable) = false];
api/end_device.proto-}
api/end_device.proto-
--
api/end_device.proto-}
api/end_device.proto-
api/end_device.proto-message SetEndDeviceRequest {
api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.nullable) = false];
api/end_device.proto-  google.protobuf.FieldMask field_mask = 2 [(gogoproto.nullable) = false];
api/end_device.proto-}
```

**Comment by johanstokking** [comment]
@kschiffer we need to get this in before `v3.0.0`. Can you file an issue?

**Comment by kschiffer** [comment]
> Looks like the field name is consistent in protos in this branch:
> 
> ```
> $ grep -C 3 -E '[[:space:]]+EndDevice[[:space:]]+[[:alnum:]_]+[[:space:]]*=[[:space:]]*[0-9]+.*' api/*.proto
> api/end_device.proto-}
> api/end_device.proto-
> api/end_device.proto-message EndDevices {
> api/end_device.proto:  repeated EndDevice end_devices = 1;
> api/end_device.proto-}
> api/end_device.proto-
> api/end_device.proto-message CreateEndDeviceRequest {
> api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false];
> api/end_device.proto-}
> api/end_device.proto-
> api/end_device.proto-message UpdateEndDeviceRequest {
> api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.embed) = true, (gogoproto.nullable) = false];
> api/end_device.proto-  google.protobuf.FieldMask field_mask = 2 [(gogoproto.nullable) = false];
> api/end_device.proto-}
> api/end_device.proto-
> --
> api/end_device.proto-}
> api/end_device.proto-
> api/end_device.proto-message SetEndDeviceRequest {
> api/end_device.proto:  EndDevice end_device = 1 [(gogoproto.nullable) = false];
> api/end_device.proto-  google.protobuf.FieldMask field_mask = 2 [(gogoproto.nullable) = false];
> api/end_device.proto-}
> ```

Because I fixed it in this branch – or what do you mean exactly?

**Pull request merged**
