### PR TITLE
Fix flaky e2e tests

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Currently, we experience flaky behavior in some e2e tests. This PR is meant to fix auth flaky behavior.

#### Changes

- Update `cypress` to the latest version
- Use admin api key to perform setup requests instead of doing the whole oauth roundtrip. This also seems to reduce CI time for 2-4 minutes

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

**Comment by kschiffer** [comment]
Unfortunately doesn't seem to solve the flakiness. We can still update cypress though.

**Review by htdvisser — APPROVED** [review]
Code-owned file `tools/mage/dev.go` looks fine

**Comment by bafonins** [comment]
@kschiffer yeah, updating `cypress` has no effect on flaky tests. however, I refactored the way we make requests to setup entities for tests and it solved the issue (at least after running e2e tests for 6 times I havent experienced any failing tests), see https://github.com/TheThingsNetwork/lorawan-stack/issues/3480. With this PR we dont need to use `cy.loginConsole` to setup tests.

**Review by kschiffer — APPROVED** [review]
Great!

**Pull request merged**
