### PR TITLE
Add default values to gateway message count

### LINKED ISSUE #766: Show 0 when no messages are sent/received
#### Summary

Show `0` when no messages are sent/received

#### Steps to Reproduce

1. Create and connect a gateway that hasn't sent a message yet
2. Go to the gateway page

#### What do you see now?

An empty value for downlink messages:

Screenshot 2019-05-28 at 15 50 18

#### What do you want to see instead?

`0`

#### Can you do this yourself and submit a Pull Request?

No

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes #766 
Apparently default values are not returned from the api

@johanstokking please check that its fixed

### CODE REVIEW

**Comment by kschiffer** [comment]
I'm ok with defaulting to 0 but can we safely assume this value when it is not provided by the API, or should we rather go with `n/a`?

**Comment by bafonins** [comment]
@johanstokking

**Comment by johanstokking** [comment]
Yes, this fallback is required. Generated protos that are returned have an `omitempty` tag (see [here](https://github.com/TheThingsNetwork/lorawan-stack/blob/master/pkg/ttnpb/gateway.pb.go#L1410)) which means that those fields are not there at all when they're empty (0 for numerics).

**Comment by htdvisser** [comment]
@kschiffer @bafonins

Since this problem is very difficult to solve in the backend (with the current specification of protocol buffers and the current versions of protobuf, grpc, grpc-gateway and jsonpb) it might be an idea to have the SDK set these "zero values" before passing them up to the UI. The API description JSON already has type information, so any number field that was requested (in the field mask) can be set to 0 if not present in the response.

**Pull request merged**
