### PR TITLE
Fix OAuth client authorizations delete request

### LINKED ISSUE #7350: OAuth client authorizations state not updated on delete
### Summary

When you delete an OAuth client from `/console/user-settings/authorizations` the state fails to update and refresh is required

### Steps to Reproduce

Open the console at `/console/user-settings/authorizations`
Click on one of the clients and click `Revoke authorization`

### Current Result

The list page will open with the same result, but refreshing the page will remove the one you deleted

### Expected Result

After clicking `Revoke authorization` the client should not be in the list

### Relevant Logs

_No response_

### URL

_No response_

### Deployment

The Things Stack Cloud

### The Things Stack Version

3.32

### Client Name and Version

_No response_

### Other Information

_No response_

### Proposed Fix

Screenshot 2024-10-21 at 12 02 23

It looks like the list request is made for awaiting the delete to succeed. I would start by checking out why

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [ ] I can help by testing the fix before it's released.

### Validation

- [ ] The fix is tested in a staging environment.
- [ ] The fix is documented in [The Things Stack Documentation](https://www.thethingsindustries.com/docs/)

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by mjamescompton**
#### Summary

Close #7350

#### Changes

- Move `attachPromise` inside dispatch

##### Steps

Open the console at /console/user-settings/authorizations
Click on one of the clients and click Revoke authorization

##### Regressions

...

#### Notes for Reviewers

https://github.com/user-attachments/assets/e9ddda7c-a475-4f6a-9d40-f581327ce425

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by ryaplots — APPROVED** [review]

**Comment by KrishnaIyer** [comment]
Nice. Is this behavior more generic across the Console? I've noticed it while deleting devices I think (don't have a screenshot for now).

**Comment by ryaplots** [comment]
@KrishnaIyer This particular issue only happened in this case. The device delete might be a different issue

**Comment by KrishnaIyer** [comment]
Isn't the promise logic the same? Basically do a `DELETE` and then a `GET` (list)?

**Comment by mjamescompton** [comment]
I search the repo for any other examples of `attachPromise(dispatch` and did not find any. Similar issues might be something else.

**Comment by ryaplots** [comment]
yes, but in this case the issue was that we were attaching the promise in the wrong place: `attachPromise(dispatch(request))`, when it should be `dispatch(attachPromise(request))`. The promise should be attached to the request and not the dispatch. I did a global search in the code base for places where we attach the promise in the wrong place and this was the only place.

**Comment by ryaplots** [comment]
@mjamescompton Please also the check the ci before merging

**Pull request merged**
