### PR TITLE
Test constructors, defaults and utilities

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Testing functionality used by #3680 
There's no usage of this functionality contrary to guidelines in order to limit the size of the PR for easier review.

#### Changes

- Add struct constructors
- Add various defaults to `test` package to reduce boilerplate across packages and promote consistency
- Add utilities to reduce boilerplate across packages

#### Notes for Reviewers

Example (intended) usage in NS:

```go
var MACStateOptions = test.MACStateOptions

func MakeMACState(dev *ttnpb.EndDevice, defaults ttnpb.MACSettings, opts ...test.MACStateOption) *ttnpb.MACState {
	v := MACStateOptions.Compose(opts...)(*test.Must(mac.NewState(dev, test.FrequencyPlanStore, defaults)).(*ttnpb.MACState))
	return &v
}

var SessionOptions = test.SessionOptions

func MakeSession(macVersion ttnpb.MACVersion, opts ...test.SessionOption) *ttnpb.Session {
	return test.MakeSession(
		SessionOptions.WithDefaultNwkKeys(macVersion),
		SessionOptions.Compose(opts...),
	)
}

type EndDeviceOptionNamespace struct{ test.EndDeviceOptionNamespace }

func (o EndDeviceOptionNamespace) Activate(defaults ttnpb.MACSettings, sessionOpts []test.SessionOption, macStateOpts ...test.MACStateOption) test.EndDeviceOption {
	return func(x ttnpb.EndDevice) ttnpb.EndDevice {
		macState := MakeMACState(&x, defaults, macStateOpts...)
		ses := MakeSession(macState.LoRaWANVersion, sessionOpts...)
		return o.Compose(
			o.WithMACState(macState),
			o.WithSession(ses),
			o.WithEndDeviceIdentifiersOptions(
				test.EndDeviceIdentifiersOptions.WithDevAddr(&ses.DevAddr),
			),
		)(x)
	}
}

var EndDeviceOptions EndDeviceOptionNamespace

func MakeEndDevice(opts ...test.EndDeviceOption) *ttnpb.EndDevice {
	return test.MakeEndDevice(
		EndDeviceOptions.WithDefaultFrequencyPlanID(),
		EndDeviceOptions.WithDefaultLoRaWANVersion(),
		EndDeviceOptions.WithDefaultLoRaWANPHYVersion(),
		EndDeviceOptions.Compose(opts...),
	)
}

func MakeOTAAEndDevice(opts ...test.EndDeviceOption) *ttnpb.EndDevice {
	return MakeEndDevice(
		EndDeviceOptions.WithDefaultJoinEUI(),
		EndDeviceOptions.WithDefaultDevEUI(),
		EndDeviceOptions.WithSupportsJoin(true),
		EndDeviceOptions.Compose(opts...),
	)
}

func MakeABPEndDevice(defaults ttnpb.MACSettings, sessionOpts []test.SessionOption, macStateOpts []test.MACStateOption, opts ...test.EndDeviceOption) *ttnpb.EndDevice {
	return MakeEndDevice(
		EndDeviceOptions.Compose(opts...),
		func(x ttnpb.EndDevice) ttnpb.EndDevice {
			if x.Multicast || !x.DevEUI.IsZero() || !x.LoRaWANVersion.RequireDevEUIForABP() {
				return x
			}
			return EndDeviceOptions.WithDefaultDevEUI()(x)
		},
		EndDeviceOptions.Activate(defaults, sessionOpts, macStateOpts...),
	)
}

func MakeMulticastEndDevice(class ttnpb.Class, defaults ttnpb.MACSettings, sessionOpts []test.SessionOption, macStateOpts []test.MACStateOption, opts ...test.EndDeviceOption) *ttnpb.EndDevice {
	return MakeABPEndDevice(defaults, sessionOpts, macStateOpts,
		EndDeviceOptions.WithMulticast(true),
		func() test.EndDeviceOption {
			switch class {
			case ttnpb.CLASS_B:
				return EndDeviceOptions.WithSupportsClassB(true)
			case ttnpb.CLASS_C:
				return EndDeviceOptions.WithSupportsClassC(true)
			default:
				panic(fmt.Sprintf("invalid multicast device class: %v", class))
			}
		}(),
		EndDeviceOptions.Compose(opts...),
	)
}

```

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Blocking #3680

**Comment by rvolosatovs** [comment]
This may be of interest for https://github.com/TheThingsNetwork/lorawan-stack/issues/3202 as well to generate device models instead of manualy creating them.

**Review by adriansmares — APPROVED** [review]

**Comment by rvolosatovs** [comment]
@htdvisser or @KrishnaIyer need your approval for merge

**Review by htdvisser — APPROVED** [review]
LGTM. I hope this will result in significant improvements to existing test code, and not just be used for new tests.

**Review by KrishnaIyer — APPROVED** [review]
LGTM

**Pull request merged**
