### PR TITLE
Merge 3.9 into 3.10

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Merge 3.9 into 3.10

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Would be nice to include https://github.com/TheThingsNetwork/lorawan-stack/pull/3133 here as well

**Comment by johanstokking** [comment]
@htdvisser or I will merge when CI passes.

**Comment by rvolosatovs** [comment]
@johanstokking sure, is there a reason why you can't just approve and I do it myself?

**Comment by johanstokking** [comment]
> @johanstokking sure, is there a reason why you can't just approve and I do it myself?

Because I'm not code owner of everything; my approval is not a green button.

**Pull request merged**
