### PR TITLE
Add email notifications preferences form

### PR DESCRIPTION
**Pull request by ryaplots**
#### Summary

Support user notification preferences (frontend) 
References #7308 

#### Changes

- Add notification preferences form
- Add link in sidebar

##### Steps

admin:
1. log in as admin into the console
2. go to `user-settings/email-notifications-settings` and see that 2 options are pre-selected because they require admin action
3. Clicking on unsubscribe all should result in a warning.
4. discard changes should discard the previously selected items if there was no update.

non-admin
1. log in as admin into the console
2. go to `user-settings/email-notifications-settings` and see that nothing is pre-selected
3. Clicking on unsubscribe all uncheck everything
4. discard changes should discard the previously selected items if there was no update.

##### Results

Screenshot 2024-10-29 at 15 35 01

Screenshot 2024-10-29 at 15 35 43

https://github.com/user-attachments/assets/713c407c-6d3f-47da-97be-47077e30844c

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by mjamescompton — APPROVED** [review]
Did not test myself, but looks good to me.

My only questions was that there is no js sdk updates required but I see that is in the backend issue.

**Comment by KrishnaIyer** [comment]
Looks good. A few updates for the text

1. Intro
> Customize your email notifications and make sure you stay aware of what you need

`Customize the notifications for which you receive emails. To see all your notifications, head to the [notifications panel](link)`

2. I think we should remove the sub-text (ex: `Receive an email when an API has been created for an entity.`) and make the Checkboxes slightly more descriptive: ex: `API Key Created` -> `API Key created for an entity`

3. `Unsubscribe from everything` -> `Turn off all email notifications`

**Comment by KrishnaIyer** [comment]
Screenshot 2024-11-11 at 15 56 56

Also a small UI thing; can we disable the checkboxes if `Turn off all email notifications` is selected?

**Review by pierrephz — CHANGES_REQUESTED** [review]
@ryaplots here is a review on the UI and UX

[Link to Figma](https://www.figma.com/design/7pBLWK4tsjoAbyJq2viMAQ/console-redesign?node-id=6525-7358&t=EKMJ3gsv1RtQWRbV-1)

email-notifications-preferences-review-14-Nov-24

I realise that after you save your changes, if you leave the page and come back, they are not updated; they are only if you refresh the page. See video below:

https://github.com/user-attachments/assets/f64f8ee1-e5ad-4721-845c-ffceab3e6637

DM for any precision or question

**Review by pierrephz — CHANGES_REQUESTED** [review]
Great, everything is good except one small thing (see screenshot)

Screenshot 2024-11-18 at 14 28 34

Please make sure the sub-label in italic and the check box label are in the same div to avoid misalignment

**Comment by ryaplots** [comment]
> Please make sure the sub-label in italic and the check box label are in the same div to avoid misalignment

The problem here was actually not the fact that both elements are not in the same div, and having them in the same div did not fix the problem. The issue here was that the description had a width: 100% which would stretch it beyond the parent. I have, however, also included the description in the checkbox element (label) because that's how we do it in the rights checkbox group for consistency.

cc: @pierrephz

**Review by pierrephz — APPROVED** [review]

**Review by mjamescompton — APPROVED** [review]

**Pull request merged**
