### PR TITLE
api: Improve documentation

### LINKED ISSUE #3167: Improve documentation for configuration_services and end_device protos
#### Summary

@rvolosatovs  , please look through these API protos and add descriptions where they are missing. It looks like many of the messages need an additional description.

`/api/configuration_services.proto`
`/api/end_device.proto`

Sub task of #252

See this PR for a gold standard API comments reference -> https://github.com/TheThingsNetwork/lorawan-stack/pull/3181/files#diff-aa11ad1a94ecc7c1db3ead25d3372bdd39c6a25dd998a2902da6e4c1cb3b8fdbR129

For example,

- Improved documentation on messages (for example, explaining what the effects of field masks are in UpdateXXXRequest messages)
- Improved documentation on methods (for example, explaining that As.SetLink does not return whether the actual linking is successful, perhaps explaining how many resources a method call consumes)
- Improved documentation on services (for example, being more clear about which components expose the services, which fields are accepted by the different EndDevice registries).
- Improved documentation on events that are published by components (for example, explaining that AS reports `as.link.start`, `as.link.stop` and `as.link.fail`, GS reports similar events, etc)

### LINKED ISSUE #3495: Improve documentation for applicationserver packages, pubsub, and web API
#### Summary

@adriansmares , please look through these API protos and add descriptions where they are missing. It looks like many of the messages need an additional description.

`applicationserver_packages.proto`
`applicationserver_pubsub.proto`
`applicationserver_web.proto`

Sub task of #252

See this PR for a gold standard API comments reference -> https://github.com/TheThingsNetwork/lorawan-stack/pull/3181/files#diff-aa11ad1a94ecc7c1db3ead25d3372bdd39c6a25dd998a2902da6e4c1cb3b8fdbR129

For example,

- Improved documentation on messages (for example, explaining what the effects of field masks are in UpdateXXXRequest messages)
- Improved documentation on methods (for example, explaining that As.SetLink does not return whether the actual linking is successful, perhaps explaining how many resources a method call consumes)
- Improved documentation on services (for example, being more clear about which components expose the services, which fields are accepted by the different EndDevice registries).
- Improved documentation on events that are published by components (for example, explaining that AS reports `as.link.start`, `as.link.stop` and `as.link.fail`, GS reports similar events, etc)

### LINKED ISSUE #3503: Improve documentation for lorawan API
#### Summary

@rvolosatovs   , please look through these API protos and add descriptions where they are missing. It looks like lots of messages could use a description.

`/api/lorawan.proto`

Sub task of #252

See this PR for a gold standard API comments reference -> https://github.com/TheThingsNetwork/lorawan-stack/pull/3181/files#diff-aa11ad1a94ecc7c1db3ead25d3372bdd39c6a25dd998a2902da6e4c1cb3b8fdbR129

For example,

- Improved documentation on messages (for example, explaining what the effects of field masks are in UpdateXXXRequest messages)
- Improved documentation on methods (for example, explaining that As.SetLink does not return whether the actual linking is successful, perhaps explaining how many resources a method call consumes)
- Improved documentation on services (for example, being more clear about which components expose the services, which fields are accepted by the different EndDevice registries).
- Improved documentation on events that are published by components (for example, explaining that AS reports `as.link.start`, `as.link.stop` and `as.link.fail`, GS reports similar events, etc)

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Add Roman's comments to NS, AS, and lorawan api protos

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3503
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3495
Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3167

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — APPROVED** [review]

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
@benolayinka generate protos with `tools/bin/mage proto:all jsSDK:definitionsClean jsSDK:definitions`

**Comment by benolayinka** [comment]
this is blocked on Docker not working on my m1 mac (not even the docker m1 beta)

**Comment by htdvisser** [comment]
The M1 Tech Preview is actually working fine for me. I guess the issue here is that the protoc images are built only for amd64, so you may need to add `--platform linux/amd64` when running the commands.

**Comment by benolayinka** [comment]
> The M1 Tech Preview is actually working fine for me. I guess the issue here is that the protoc images are built only for amd64, so you may need to add `--platform linux/amd64` when running the commands.

alright docker working, but where do I need to add the "--platform linux/amd64" flag?

**Comment by htdvisser** [comment]
Somewhere here: 

https://github.com/TheThingsNetwork/lorawan-stack/blob/95e998dd8c579df0126e9381526bd737d080e966/tools/mage/proto.go#L72-L77

Note that I haven't tried this myself.

**Comment by benolayinka** [comment]
> Somewhere here:
> 
> https://github.com/TheThingsNetwork/lorawan-stack/blob/95e998dd8c579df0126e9381526bd737d080e966/tools/mage/proto.go#L72-L77
> 
> Note that I haven't tried this myself.

Tried this but it looks like the platform needs to be specified when the image is built, not run.

```
tools/bin/mage proto:all jsSDK:definitionsClean jsSDK:definitions
unknown flag: --platform linux/amd64
See 'docker run --help'.
Error: failed to generate protos: running "docker run --platform linux/amd64 --rm --user 501:20 --mount type=bind,src=/Users/ben/lorawan-stack/api,dst=/Users/ben/lorawan-stack/api --mount type=bind,src=/Users/ben/lorawan-stack/pkg/ttnpb,dst=/out/go.thethings.network/lorawan-stack/v3/pkg/ttnpb --mount type=bind,src=/Users/ben/lorawan-stack/sdk/js,dst=/Users/ben/lorawan-stack/v3/sdk/js -w /Users/ben/lorawan-stack thethingsindustries/protoc:3.1.28-tts -I/Users/ben --swagger_out=allow_merge,merge_file_name=api:/Users/ben/lorawan-stack/api /Users/ben/lorawan-stack/api/*.proto" failed with exit code 125
```

**Pull request merged**
