### PR TITLE
util: Update docs in release template

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Add documentation version update and api docs to release template

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — COMMENTED** [review]
I don't think these instructions belong here. Instead, I would suggest that here we add a step to create a release issue in the documentation repository. In the documentation repository we'd then add an issue template for releases, where we list the things that need to be updated, including the API updates, but also creating the "what's new" page, etc.

**Comment by benolayinka** [comment]
> I don't think these instructions belong here. Instead, I would suggest that here we add a step to create a release issue in the documentation repository. In the documentation repository we'd then add an issue template for releases, where we list the things that need to be updated, including the API updates, but also creating the "what's new" page, etc.

Created a [release checklist in the documentation](https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/233), and updated this PR to link to that

**Comment by htdvisser** [comment]
This is blocked on https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/233

**Comment by benolayinka** [comment]
> This is blocked on [TheThingsIndustries/lorawan-stack-docs#233](https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/233)

No longer blocked

**Review by htdvisser — APPROVED** [review]

**Pull request merged**
