### PR TITLE
Support Redis 7

### LINKED ISSUE #5416: Support Redis 7
#### Summary

Support Redis 7

This issue is _not_ about using Redis 7.0.0 features, but making sure The Things Stack works as intended with Redis 7.0.0.

#### Why do we need this?

To make sure that users do not need to downgrade Redis to work with The Things Stack.

#### What is already there? What do you see now?

We currently have support for Redis 6.2.x. 

As of now, the only known issue is a failing test:

```
--- FAIL: TestApplicationUplinkQueue (0.01s)
    --- FAIL: TestApplicationUplinkQueue/Consumers=1 (0.01s)
        --- FAIL: TestApplicationUplinkQueue/Consumers=1/1st_run (0.00s)
            doc.go:66: 
                /home/runner/work/lorawan-stack/lorawan-stack/pkg/networkserver/internal/test/shared/application_uplink_queue.go:140
                Expected: nil
                Actual:   'got 3, wanted 2'
            doc.go:66: 
                /home/runner/work/lorawan-stack/lorawan-stack/pkg/networkserver/internal/test/shared/application_uplink_queue.go:339
                Expected: true
                Actual:   false
        application_uplink_queue_test.go:39: Skipping 2nd run
FAIL
FAIL	go.thethings.network/lorawan-stack/v3/pkg/networkserver/redis	0.083
```

Which may imply an API change or an API interpretation issue, which may have larger effects that we currently do not test or do not trigger a test failure.

#### What is missing? What do you want to see?

Make sure The Things Stack works with Redis 7.0.

#### How do you propose to implement this?

Lots of testing

#### How do you propose to test this?

CI pass and integration testing

#### Can you do this yourself and submit a Pull Request?

Can review

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/5416
References https://github.com/go-redis/redis/pull/2110

#### Changes

- Upgrade to `go-redis` `9.0.1`
  - The error in the linked issue is caused by our use of `XAutoClaim`. As part of Redis 7.0, a new return parameter was added to `XAutoClaim` - the entries that were part of the PEL but were deleted in the meantime. This mismatch (2 vs 3 return values) was reported in the linked issue. We do not seem to have a semantic mismatch.
  - The upgrade itself is done in two steps - change every `/v8` to `/v9` + upgrade `go.mod`, then fix the API changes.
  - Most of the API changes were minor - the removal of `Close()` from pipeliners and the fact that `XAdd` parameters now require an explicit approximation parameter.
  - An important change is that Redis operations can no longer be asynchronously cancelled using `context.WithCancel` or `context.WithTimeout`. Call sites that previously blocked indefinitely (`XRead`/`XReadGroup`) now loop in tests, but block indefinitely in production code.

#### Testing

CI.

##### Regressions

Fundamentally nothing changes - this is only a database library change, so the only regressions that we would feel would be regressions that are in the library itself.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by KrishnaIyer — APPROVED** [review]
Looks good to my (not so experienced) eyes.

**Review by johanstokking — COMMENTED** [review]
LGTM

Please hold merge until there's a more stable `v9` release.

Issues like https://github.com/go-redis/redis/issues/2139 might be concerning.

**Review by htdvisser — APPROVED** [review]
Nothing to add, but let's indeed wait for a stable v9 release.

**Comment by adriansmares** [comment]
No new tag since [v9.0.0-beta.1](https://github.com/go-redis/redis/releases/tag/v9.0.0-beta.1). Still waiting on a stable release.

---

16 Oct 2022 update: Updated to [v9.0.0-rc.1](https://github.com/go-redis/redis/releases/tag/v9.0.0-rc.1).
Also contains a semantics update for `XRead`/`XReadGroup`, since now Redis operations cannot be asynchronously cancelled anymore.

---
5 Dec 2022 update: Updated to [v9.0.0-rc.2](https://github.com/go-redis/redis/releases/tag/v9.0.0-rc.2).
No semantical changes.

**Comment by johanstokking** [comment]
Is this ready for review and good to go?

**Comment by adriansmares** [comment]
> Is this ready for review and good to go?

The PR is ready for review, but we haven't had an official release of `go-redis` `v9` - the latest release is [`rc2`](https://github.com/go-redis/redis/releases/tag/v9.0.0-rc.2) from November last year.

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Please re-request review when there are non-dependency code changes.

**Pull request merged**
