### PR TITLE
doc: Add CRLF to basics station guide

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

https://github.com/TheThingsIndustries/lorawan-stack-support/issues/108

#### Changes

- Add CRLF note to basics station docs

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by KrishnaIyer — APPROVED** [review]
Maybe add my little `perl` script for unix-bases OS users to quickly do this?
```
echo "Authorization: Bearer NNSXS.xxxxx" | perl -p -e 's/\r\n|\n|\r/\r\n/g' 
```

**Comment by benolayinka** [comment]
> Maybe add my little `perl` script for unix-bases OS users to quickly do this?
> 
> ```
> echo "Authorization: Bearer NNSXS.xxxxx" | perl -p -e 's/\r\n|\n|\r/\r\n/g' 
> ```

This work to save the output? 

```
echo "Authorization: Bearer NNSXS.xxxxx" | perl -p -e 's/\r\n|\n|\r/\r\n/g'  > cups.key
```

**Comment by KrishnaIyer** [comment]
Yups. Same process for LNS.. :)

**Review by KrishnaIyer — APPROVED** [review]
LGTM

**Pull request merged**
