### PR TITLE
Retrieve non zero fields during set

### PR DESCRIPTION
**Pull request by adriansmares**
#### Summary

References https://github.com/TheThingsIndustries/lorawan-stack/pull/3850

This PR changes the mechanism used to retrieve fields from the NS end device store to retrieve only non zero fields. While for normal fields this is equivalent to the existing `SetFields` semantics, for `oneof` fields this is not the case - `SetFields` errors out if one tries to copy the fields while specifying the wrong source. In order to deal with this limitation, we initially request all of the end device fields from the underlying store, and then retrieve only the non zero ones.

Note that this change affect _only_ the fields retrieved by the NS in order to validate the patch - the fields updated by the patch itself still cannot violate the `oneof` limitations.

#### Changes

- Retrieve non zero fields from the NS end device store.

#### Testing

Tested as part of https://github.com/TheThingsIndustries/lorawan-stack/pull/3850 - no additional testing is needed.

##### Regressions

This does not change the RPC semantics, because the updated fields are unaffected by this change - if the caller violates the `oneof` rule, updating the end device will fail.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by johanstokking** [comment]
> ##### Regressions
> 
> This does not change the RPC semantics, because the updated fields are unaffected by this change - if the caller violates the `oneof` rule, updating the end device will fail.

OK, but we will get all fields first, which is inefficient when moving to another store, right?

Do we need something similar in other end device registry stores?

**Comment by adriansmares** [comment]
> OK, but we will get all fields first, which is inefficient when moving to another store, right?

This is correct, if the separate store implementation really can go very deep nesting wise - please note that the `oneof`s are 2-3 layers down the message wrapping (`(pending_)mac_state` -> `(current|desired)_parameters` -> `relay` -> an actual `oneof` finally; or `mac_settings` -> `(desired_)relay` -> an actual `oneof`). 

A possible solution is to simplify the fields such that they stop at the `oneof` fields. I would prefer that we do that if we change the implementation and the implementation really can benefit from such an optimization.

> Do we need something similar in other end device registry stores?

Only the NS related fields currently are `oneof`centric. Other (end device) stores don't use `oneof`s.

---

Another point here is that this change affects strictly the `Set` RPC (which is used to create/update the end device, which is rare) - the internal end device updates aren't affected by this change.

**Comment by johanstokking** [comment]
> A possible solution is to simplify the fields such that they stop at the `oneof` fields.

How do you mean?

> I would prefer that we do that if we change the implementation and the implementation really can benefit from such an optimization.

"The implementation" is the store implementation?

**Comment by adriansmares** [comment]
> How do you mean?

Let's take a concrete example - the validation code wants the following paths:

```
"mac_state.current_parameters.relay.mode.served.backoff",
"mac_state.current_parameters.relay.mode.served.mode.always",
"mac_state.current_parameters.relay.mode.served.mode.dynamic.smart_enable_level",
"mac_state.current_parameters.relay.mode.served.mode.end_device_controlled",
"mac_state.current_parameters.relay.mode.served.second_channel.ack_offset",
"mac_state.current_parameters.relay.mode.served.second_channel.data_rate_index",
"mac_state.current_parameters.relay.mode.served.second_channel.frequency",
"mac_state.current_parameters.relay.mode.served.serving_device_id",
"mac_state.current_parameters.relay.mode.serving.cad_periodicity",
"mac_state.current_parameters.relay.mode.serving.default_channel_index",
"mac_state.current_parameters.relay.mode.serving.limits.join_requests.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.join_requests.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.notifications.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.notifications.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.overall.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.overall.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.reset_behavior",
"mac_state.current_parameters.relay.mode.serving.limits.uplink_messages.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.uplink_messages.reload_rate",
"mac_state.current_parameters.relay.mode.serving.second_channel.ack_offset",
"mac_state.current_parameters.relay.mode.serving.second_channel.data_rate_index",
"mac_state.current_parameters.relay.mode.serving.second_channel.frequency",
"mac_state.current_parameters.relay.mode.serving.uplink_forwarding_rules"
```

`mac_state.current_parameters.relay.mode` here is a `oneof`, so it is not legal to use `SetFields` with all of these paths (because it is unclear which one is actually in the source entity).

The proposal in this PR is to retrieve all of the top level fields, then decide which paths are non zero using `NonZeroFields`. If the `mode` is `serving`, we now have the paths:

```
"mac_state.current_parameters.relay.mode.serving.cad_periodicity",
"mac_state.current_parameters.relay.mode.serving.default_channel_index",
"mac_state.current_parameters.relay.mode.serving.limits.join_requests.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.join_requests.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.notifications.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.notifications.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.overall.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.overall.reload_rate",
"mac_state.current_parameters.relay.mode.serving.limits.reset_behavior",
"mac_state.current_parameters.relay.mode.serving.limits.uplink_messages.bucket_size",
"mac_state.current_parameters.relay.mode.serving.limits.uplink_messages.reload_rate",
"mac_state.current_parameters.relay.mode.serving.second_channel.ack_offset",
"mac_state.current_parameters.relay.mode.serving.second_channel.data_rate_index",
"mac_state.current_parameters.relay.mode.serving.second_channel.frequency",
"mac_state.current_parameters.relay.mode.serving.uplink_forwarding_rules"
```

Which can be copied because they all fall under the same `oneof`.

The other way, not implemented here, is to detect that we have subfields of the `oneofs` via `HasAnyField`, and if yes to remove all of the subfields of the `oneof` and replace the retrieved field from the store with the `oneof` field itself (here it would be `mac_state.current_parameters.relay.mode`).

How this would look like is that you look at the original list, you find that there are subfields of `mac_state.current_parameters.relay.mode` in it, and you replace them with `mac_state.current_parameters.relay.mode`. After the store has returned, you do the `NonZeroFields` logic in order to really copy only the bottom level fields which you need.

The challenge here is that we don't have a systematic way of doing this (reduce this set of paths to their nearest `oneof`). We would need some help from the paths plugin in order to be able to do this.

> "The implementation" is the store implementation?

I meant that I would prefer to optimize the fields which the RPC layer requests from the store layer once the store layer really would benefit from the fine grained field access. Again, this is the `Set` RPC - the correctness here is more important than raw performance, especially with the 2.5k lines of validation code which are questionably maintainable.

**Comment by johanstokking** [comment]
If I understand correctly what we'd need is to get the other fields in the oneof to determine which one is set. When setting fields, the other ones should be reset. Indeed our field mask plugin should provide a helper to add the other fields of the oneof to a field mask if there's a (sub) path of the oneof selected. 

> > "The implementation" is the store implementation?
> 
> I meant that I would prefer to optimize the fields which the RPC layer requests from the store layer once the store layer really would benefit from the fine grained field access.

I understand and I would be fine with this for now and in this context.

If we go with a columnar store, we'd probably need to explicitly store the selected oneof field in a dedicated column. This is because all fields at flattened as columns, so there's no notion of a set field anymore.

If we go with a document store, we probably benefit from the same logic as described above.

**Comment by adriansmares** [comment]
> If I understand correctly what we'd need is to get the other fields in the oneof to determine which one is set. When setting fields, the other ones should be reset. Indeed our field mask plugin should provide a helper to add the other fields of the oneof to a field mask if there's a (sub) path of the oneof selected.

You have understood the details correctly.

Is it sufficient that we have an issue we can track with the details of this change ? Are there other changes you would like to see in this particular PR at the moment ?

**Comment by johanstokking** [comment]
> Is it sufficient that we have an issue we can track with the details of this change ? Are there other changes you would like to see in this particular PR at the moment ?

Yes the issue is sufficient.

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
