### PR TITLE
doc: Restructure

### LINKED ISSUE #2358: Restructure docs
#### Summary

Change doc structure from
- Guides
- Concepts
- Components
- Reference

to
- Getting started
- Devices
- Gateways
- The Things Stack
- Integrations
- Reference

#### Why do we need this ?

Restructure docs to
- Reflect how users search for help
- Flatten hierarchy
- Match conceptual flow of data
- Add some useful sections

#### Current structure

- Guides
	- getting started
		- installation
		- certs
		- configuration
		- running the tts stack
		- console
			- create gateway
			- create app
			- create end device
		- command-line interface
		- working with data
	- connecting gateways
	- basic user management
	- working with events
	- downlink queue operations
	- class c and multicast
	- generate qr code
	- web ui branding
- Concepts
	- end device templates
	- email templates
	- webhook templates
- Components
	- identity server
	- gateway server
	- network server
	- application server
	- join server
	- console
	- qr code generator
	- command-line interface
	- device template converter
	- gateway configuration server
- Reference
	- api
	- configuration
	- application server data
	- application packages
	- email templates
	- end device templates
	- webhook templates
	- interoperability repo
	- networking

#### Proposed structure

- Getting started
	- installation
		- certs
		- configuration
		- running the tts stack
	- console
		- create gateway
		- create app
		- create end device
	- command-line interface
	- working with data
	- connecting gateways
	- basic user management
	- working with events
	- downlink queue operations
	- class c and multicast
	- generate qr code
	- web ui branding
- Devices
	- device registration
	- working with data
	- device templates
- Gateways
	- connect a gateway
	- common gateways
- The Things Stack
	- components
	- cli
	- console
	- ...
- Integrations
	- webhook templates
	- email templates
	- mqtt
	- data formats
	- application packages
- Reference
	- api
	- configuration
	- interoperability
	- glossary
	- port allocations

#### How do you propose to document this?

This is a change to documentation.

#### Can you do this yourself and submit a Pull Request?

Yes. Feedback appreciated, especially @htdvisser @johanstokking @wienke @laurensslats

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Closes #2358 

#### Changes

Change doc structure from
- Guides
- Concepts
- Components
- Reference

to
- Getting started
- Devices
- Gateways
- Integrations
- Reference

#### Notes for Reviewers

Restructure docs to
- Reflect how users search for help
- Flatten hierarchy
- Match conceptual flow of data
- Add some useful sections

Removed The Things Stack section referenced in #2358 because it made navigation confusing and was unnecessary. 

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [ ] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by kschiffer** [comment]
New structure is nice, but somehow the layout looks broken now for me:
image

**Comment by benolayinka** [comment]
> @kschiffer I can't reproduce in Brave: 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
> 
> For me the overview image is broken though;
> 
> Screenshot 2020-04-17 at 10 20 23
> 
> Can you use a Hugo ref for this?

Pushed a fix for the overview image. I tried a Hugo ref, but I couldn't get it to work for an svg.

**Comment by benolayinka** [comment]
> New structure is nice, but somehow the layout looks broken now for me:
> image

Is that a css issue? Looks like this for me in Chrome 80

Screenshot 2020-04-17 at 11 24 14

**Comment by benolayinka** [comment]
> image
> 
> We may have to hide some items from the navbar on smaller screens to prevent the "Get The Things Stack" item from being pushed off the page.
> 
> Other than that, this looks okay to me.

We could change the navbar-burger, navbar-start and navbar-end media queries to change when the burger kicks in.. currently set at 1024px. Should I change this, or let whoever handles the template do it?

Screenshot 2020-04-20 at 11 07 35

**Comment by htdvisser** [comment]
I don't think tweaking the breakpoints is the right solution here.

**Comment by benolayinka** [comment]
> I don't think tweaking the breakpoints is the right solution here.

But where should the menus go if we hide them? They should still be accessible somehow, right?

**Comment by laurensslats** [comment]
1 important point. **INSTALLATION** is not shown at the website as of now. 
**INSTALLATION** is only applicable to `The Things Stack`, NOT to `The Things Enterprise Stack`. (At some point we will allow people to run the stack on-premises as a paid service, but we don't have this yet.)

Rest looks good to me.

**Comment by benolayinka** [comment]
> 1 important point. **INSTALLATION** is not shown at the website as of now.
> **INSTALLATION** is only applicable to `The Things Stack`, NOT to `The Things Enterprise Stack`. (At some point we will allow people to run the stack on-premises as a paid service, but we don't have this yet.)
> 
> Rest looks good to me.

Pushed with changes from @laurensslats, @kschiffer pls review?
- Moved class `c & multicast, generate qr codes, downlink queue ops` to `devices`
- Moved `Web UI branding` to reference

Proposing to close this PR and open issues to fix hidden items and enterprise vs open source docs

**Comment by johanstokking** [comment]
@benolayinka OK, please (re-)request review when ready

**Comment by benolayinka** [comment]
> If you click Getting Started, I think we should go straight to the first page (Installation) with the other steps in the menu on the left
> 
> Other than that, I'm happy with this change!

I agree, but it requires a change to the theme, and I think should be a separate PR. All other top level menus also display the 'card' layout, and clicking on any card loses the reference to the parent section. 

All sections would be improved by this - replacing the 'card' layout with a two-column sidebar layout, and automatically showing the first section or an overview.

Devices first level:
Screenshot 2020-04-22 at 16 49 27

Devices second level: (no easy way to navigate to other devices menus)
Screenshot 2020-04-22 at 16 49 34

**Comment by johanstokking** [comment]
OK, but can't you link directly to Installation instead of linking to the Getting Started overview?

**Comment by benolayinka** [comment]
> OK, but can't you link directly to Installation instead of linking to the Getting Started overview?

Yep, but that's confusing because then there's no way to get to the rest of the Getting Started items:

You would end up directly here (wrong menu depth in the sidebar)
Screenshot 2020-04-23 at 08 37 38

**Pull request merged**
