### PR TITLE
Comply with go module naming scheme

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Currently it is not possible to import `go.thethings.network/lorawan-stack` or any of the subpackages outside of this repository, because the structure does not comply with go module naming scheme. Example:
```
$ go mod tidy
go: finding module for package go.thethings.network/lorawan-stack/pkg/ttnpb
go: finding module for package go.thethings.network/lorawan-stack/pkg/encoding/lorawan
go: finding module for package go.thethings.network/lorawan-stack/pkg/types
github.com/rvolosatovs/lorawan-codec imports
	go.thethings.network/lorawan-stack/pkg/encoding/lorawan: module go.thethings.network/lorawan-stack@latest found (v3.0.0-pre+incompatible), but does not contain package go.thethings.network/lorawan-stack/pkg/encoding/lorawan
github.com/rvolosatovs/lorawan-codec imports
	go.thethings.network/lorawan-stack/pkg/ttnpb: module go.thethings.network/lorawan-stack@latest found (v3.0.0-pre+incompatible), but does not contain package go.thethings.network/lorawan-stack/pkg/ttnpb
github.com/rvolosatovs/lorawan-codec imports
	go.thethings.network/lorawan-stack/pkg/types: module go.thethings.network/lorawan-stack@latest found (v3.0.0-pre+incompatible), but does not contain package go.thethings.network/lorawan-stack/pkg/types
```

#### Changes

- Fix go module name and imports

#### Notes for Reviewers

Did this via https://github.com/marwan-at-work/mod

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
To see this in action, try importing `github.com/rvolosatovs/lorawan-stack/v3`:
```
$ go mod tidy
go: finding module for package github.com/rvolosatovs/lorawan-stack/v3/pkg/ttnpb
go: finding module for package github.com/rvolosatovs/lorawan-stack/v3/pkg/encoding/lorawan
go: finding module for package github.com/rvolosatovs/lorawan-stack/v3/pkg/types
go: downloading github.com/rvolosatovs/lorawan-stack/v3 v3.7.3
go: found github.com/rvolosatovs/lorawan-stack/v3/pkg/encoding/lorawan in github.com/rvolosatovs/lorawan-stack/v3 v3.7.3
go: github.com/rvolosatovs/lorawan-stack/v3@v3.7.3 requires
	github.com/blang/semver@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Sure, the users still need to copy-paste our replacements from `go.mod` to actually make it work, but at least they can import our package at all.

**Comment by johanstokking** [comment]
We did not design this repository to be imported by other projects. This is not a library and we should not position it as such.

I rather see effort in going renaming `pkg` to `internal`, and cherry-pick some functionality later in a go mod compliant way via `pkg`.

**Comment by rvolosatovs** [comment]
> Also this is not closing an issue which was set to this milestone.

Yes, I needed this functionality to in order to import `pkg/encoding/lorawan`

> We did not design this repository to be imported by other projects. This is not a library and we should not position it as such.
> 
> I rather see effort in going renaming `pkg` to `internal`, and cherry-pick some functionality later in a go mod compliant way via `pkg`.

For this to work we would need to have multiple `go.mod`/`go.sum` files and maintain several modules in one repository. (and several tags as well)

What is the benefit of that? Why not simply comply with what `go mod` expects and have it all working already now forever without all the maintenance burden?
The only potential (subjective) downside to doing this I see is having to explicitly specify `v3` in import statements, so they are now 3 characters longer, which IMO is reasonable.

**Comment by johanstokking** [comment]
Let's also make it easy for ourselves and do this when `develop` and `master` are on par, i.e. on the 3.8.0 release this week

**Pull request merged**
