### PR TITLE
Use per-gateway downlink tokens for LoRa Basics Station

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Refs #7182 

#### Changes

- Use per-gateway downlink tokens in the frontend connection.
- Update tests.

##### Steps

This is mostly covered by unit tests.

##### Regressions

Screenshot 2024-08-05 at 14 28 15

#### Notes for Reviewers

~- This is still draft until CI is complete and I run some tests with a gateway.~
- The alternative approach is to store the tokens in `io.Connection` but this means that we'll have to refactor all the frontends to use it and that's more work than what the issue requires.
- We also need an update to the `tabshubs` frontend and I'll pick that up during the merge.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]
LGTM

**Comment by johanstokking** [comment]
This should be captured by the common `iotest`. So if CI passes, this should work. Why is this draft?

**Comment by KrishnaIyer** [comment]
> So if CI passes, this should work. Why is this draft?

CI hasn't passed. I'm checking the frontend actions since the failures are persistent. Plus I'd like to do a quick regression test with a physical gateway.

**Comment by KrishnaIyer** [comment]
Basic regression tests work and CI passed after a few retries. This can be merged

**Pull request merged**
