### PR TITLE
Send join-accept to AS on successful scheduling

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3476

#### Changes

- Send join-accept to AS on successful scheduling

#### Testing

Unit tests

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Blocked by https://github.com/TheThingsNetwork/lorawan-stack/pull/3263

**Comment by johanstokking** [comment]
@rvolosatovs do you have a commit range to review while this is blocked on a huge PR?

**Comment by rvolosatovs** [comment]
> @rvolosatovs do you have a commit range to review while this is blocked on a huge PR?

Yes, https://github.com/TheThingsNetwork/lorawan-stack/pull/3491/commits/7735bc5b3b713d776be7a90cdb37a72b3b134b40

**Comment by adriansmares** [comment]
Just to make sure that I understand - previously the `JoinAccept` was enqued (and dequed then sent to the AS) before the pending session was actually saved / commited ?

**Comment by rvolosatovs** [comment]
`PendingSession` is only set once `JoinAccept` is scheduled on GS

Before the `JoinAccept` would be sent after an accept was received from JS
Now the `JoinAccept` is sent after successful GS scheduling

**Comment by adriansmares** [comment]
> `PendingSession` is only set once `JoinAccept` is scheduled on GS
> 
> Before the `JoinAccept` would be sent after an accept was received from JS
> Now the `JoinAccept` is sent after successful GS scheduling

This actually may explain other issues that we're seeing - if the AS will try to be smart and submit a queue recalculation (either due to invalidation or nack) for both sessions (because it thinks that `PendingSession` exists in the NS) the NS will reject it if the `JoinAccept` wasn't scheduled it, and thus render the sessions out-of-sync. This links back to JoinAccepts not getting scheduled due to missing peers.

**Review by adriansmares — APPROVED** [review]
The commit that fixes this LGTM but can't we backport this to `v3.10` ? It's a bit of a long way until `v3.11`.

**Comment by rvolosatovs** [comment]
I think we really should move 3.11 forward, because there are just too many changes already.
We can backport this to 3.10 if we delete the tests

**Review by htdvisser — COMMENTED** [review]
Please re-request review when unblocked and ready for review.

**Review by johanstokking — COMMENTED** [review]
Same

**Comment by rvolosatovs** [comment]
The commit in question is already reviewed and did not change, merging

**Pull request merged**
