### PR TITLE
Fix infinite loop in Redis

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Fixes infinite loop in NS Redis introduced by #1524 

#### Changes

- Fix `XReadGroup` call - split `XReadGroup` for pending messages and `XReadGroup` for new messages in 2 calls, since `XReadGroup` for pending messages does not block

#### Notes for Reviewers

I misread https://redis.io/commands/xreadgroup
After reading this:
> Any other ID, that is, 0 or any other valid ID or incomplete ID (just the millisecond time part), will have the effect of returning entries that are pending for the consumer sending the command with IDs greater than the one provided. So basically if the ID is not >, then the command will just let the client access its pending entries: messages delivered to it, but not yet acknowledged. Note that in this case, both BLOCK and NOACK are ignored.

I assumed the `XReadGroup` would still block if there are multiple streams being read and there were no pending messages, but that turned out to not be the case. (https://github.com/antirez/redis/issues/6587)

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@htdvisser that is not the fix - the fix is separately processing the pending messages and then blocking for new ones, since Redis does not allow doing both in 1 call.
Creation was not supposed to be in the loop as well.

**Comment by htdvisser** [comment]
Okay, can you clarify that in the **Changes** section of the PR?

And maybe smart to add some comments to the code to warn future developers about this.

**Comment by rvolosatovs** [comment]
I think current implementation is actually "more correct" and should be clear enough as is. In any case this behavior is(and should be) documented at https://redis.io/commands/xreadgroup, no need to document Redis commands here.

**Comment by htdvisser** [comment]
I'm not saying we should document Redis commands. I'm just proposing to warn future developers about this "surprise". If you don't think that's necessary, fine.

**Pull request merged**
