### PR TITLE
Use channels from the frequency plan for ABP resets

### LINKED ISSUE #196: Dropped messages - uplink_channel_not_found on migrated devices
**Summary:** 
Device that are migrated (devices that have joined on an other NS) and that are created on the stack using the cli (they have not joined on the stack), may send uplinks on channels that are not one of the 3 default channels on EU_863_870 (868100000, 868300000, 868500000).
Those uplinks on not default channels are dropped. 

**Steps to Reproduce:** 
When the device is created using the cli, the MACState Channels are initialized to the defaultChannels of the FP. (only 3 channels for  EU_863_870).
Uplinks received on  channels not declared in the MACState are dropped.

**What do you see now?**
 DEBUG Dropping message                         dev_addr=FC0068B1 error=error:pkg/networkserver:uplink_channel_not_found (uplink channel not found) gateway_eui=00000008004A5D13 gateway_uid=eui-00000008004a5d13 namespace=gatewayserver/io/udp
I have not seen a way to configure the channels on the cli.

Note that I think eventually, a MAC command will be send to adjust channels on the device, and therefore the MACState current channels will be extended to all possible values, and eventually, thinks may get ok, but that may take forever.

**What do you want to see instead?**
All EU Channels set in MACState upon creation in this case, to avoid message drops

**How do you propose to implement this?**
ability to change channels in cli. Having a custom FP is a workaround, but not ideal. 

**Environment:**
all

**What can you do yourself and what do you need help with?**
not sure what is the best solution. I wonder why MacState is initialised with only this subset of channels (Default channels).

### PR DESCRIPTION
**Pull request by rvolosatovs**
**Summary:**

Closes #196 

**Changes:**

- Assume ABP devices have channels from the selected frequency plan configured in MAC layer on resets

### CODE REVIEW

**Comment by htdvisser** [comment]
Are you sure this is correct? As far as I know, ABP devices reset to band channels, and not frequency plan.

**Comment by rvolosatovs** [comment]
I also was under impression, that devices by default reset to band channels, if they don't the users can specify https://github.com/TheThingsNetwork/lorawan-stack/blob/f501af78810982988835e80773bca280de92c229/api/end_device.proto#L220
According to @johanstokking the ABP should have our frequency plan channels hard-coded, which I also doubt.

**Comment by johanstokking** [comment]
It depends on what people understand under "personalization". If it is everything that's otherwise part of the join procedure, which does contain CFList/ChMask, then we should assume that the device has the channel plan.

I'm not sure anymore what we should do with this. Only using the band defaults may result in the `uplink_channel_not_found` errors.

@rvolosatovs are those `factory_preset_frequencies` including the band defaults?

**Comment by rvolosatovs** [comment]
This is from BE spec: 
2019-02-28-14 20 32-screenshot
I suppose it means that the band channels are not there

**Comment by htdvisser** [comment]
Nothing in the LoRaWAN or Backend Interfaces specs mentions that ABP devices need to have any frequency plan channels configured. The only requirement comes from the Regional Parameters spec for EU and similar:

> The network channels can be freely attributed by the network operator. However the three following default channels must be implemented in every EU868MHz end-device.

Therefore I'd say that devices that don't specify `FactoryPresetFreqs` are assumed to have only those mandatory default channels configured.

**Comment by johanstokking** [comment]
OK, sorry for the confusion!

**Pull request closed without merging**
