### PR TITLE
Set AU_915_928 duty-cycle to 1%

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Set AU_915_928 duty-cycle to 1%

cc @ama9910

#### Changes

- Change from 100% to 1%

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [ ] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by johanstokking** [comment]
@ama9910 can you provide the source link (or document name + year + page)?

Note to self; file issue to reduce the many `DevStatusReq`

**Comment by ama9910** [comment]
@htdvisser @johanstokking I can't find this documented anywhere so have contacted ACMA. ETA 29-Nov-2019.

**Comment by MrAPierce** [comment]
I cant find it either. it will be interesting to see what the ACMA say. every ACMA document that I have read states that the frequency hopping is limiting factor, even going through Australian certification of devices, hopping was there main concern for the ISM band here.

I don't believe Australia is bound by the 1% duty cycle like other countries. @ama9910 let us know what you find out 👍

**Comment by johanstokking** [comment]
Blocked by confirmation from ACMA

**Comment by ama9910** [comment]
Well, it looks like I was mistaken. The ACMA have confirmed there is no duty cycle requirement for Australia! Pity. As TTN users we are careful with the band-plan (30 secs per day per device). Non-TTN users, who I thought were limited to 1%, are actually unlimited.

**Comment by johanstokking** [comment]
Actually this is good news to me. Uplink should indeed be limited in the light of overall network capacity – we will add feedback in The Things Stack – but 1% for the entire band would be very restrictive, significantly more restrictive than EU 863-867 MHz. Firmware updates would not be practically possible. Gateways should not be too busy transmitting, but with many deployments having devices covered by 2, 3 gateways or more, and class C and B picking up, having downlink capacity available is good news.

**Pull request closed without merging**
