### PR TITLE
Fix search results ordered by `last seen at`

### PR DESCRIPTION
**Pull request by nicholaspcr**
#### Summary

Refers to https://github.com/TheThingsIndustries/lorawan-stack-support/issues/895
Where the act of specifying the `last_seen_at` order to the search would return an error instead of the array of devices in the proper order.

#### Changes

- Added `last_seen_at` to the allowed list of values for the `order` field in the SearchEndDevicesRequest
- ...

#### Testing

Manual testing, replicated what is on the video of the issue linked in the summary.

##### Regressions

This is a bug fix with the only alteration being the addition of a value in a request field, does not break the API or any other components.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by adriansmares — APPROVED** [review]

**Comment by kschiffer** [comment]
Also, note that currently devices that were never seen are ordered first instead of last (when ordering ascending).

**Review by johanstokking — APPROVED** [review]

**Comment by nicholaspcr** [comment]
>Also, note that currently devices that were never seen are ordered first instead of last (when ordering ascending).

I don't notice this happening @kschiffer , took some prints in terms of what is going on since I might have misunderstood something.

The image bellow is sorting the devices by ascending order via ID which has the logo of `arrow_drop_down`:
image

I made 4 devices, the last called `dev-4` and being the only one never seen before. Ordering by ascending it should be last, which is what is shown in the picture bellow
image

**Comment by kschiffer** [comment]
Ah ok, seems like a false alert then. I was essentially echoing this post https://www.thethingsnetwork.org/forum/t/upgrade-to-the-things-network-v3-23-1-completed/60333/4

**Comment by nicholaspcr** [comment]
> Ah ok, seems like a false alert then. I was essentially echoing this post https://www.thethingsnetwork.org/forum/t/upgrade-to-the-things-network-v3-23-1-completed/60333/4

Okay, I will write it there to ask for more information on what exactly he meant by that.

**Pull request merged**
