### PR TITLE
Move API key name to first column

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/875

>  then maybe we should make the columns ID, name, rights.

Screenshot 2019-07-02 at 09 58 58

### CODE REVIEW

**Comment by johanstokking** [comment]
Yeah good point. If we keep the sorting by ID (makes sense, `name` is optional), then maybe we should make the columns ID, name, rights.

**Comment by bafonins** [comment]
> then maybe we should make the columns ID, name, rights.

How is this better than the order before?

**Comment by johanstokking** [comment]
> > then maybe we should make the columns ID, name, rights.
> 
> How is this better than the order before?

The name was burried on the right

**Comment by bafonins** [comment]
updated description

**Comment by kschiffer** [comment]
The ID value is very unhelpful IMO. I don't see any user scanning the table by a cryptic hash value. If we can, we should really sort by creation date or the name value. We might even consider making the name field mandatory, or setting default values like `API Key 1`, which I would recommend. We can then hide or at least abbreviate the ID field in the table view (that is, if there is no essential use of the ID value that I have missed).

**Pull request merged**
