### PR TITLE
Reorganize protos and initialize Buf module

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Open source counterpart of https://github.com/TheThingsIndustries/lorawan-stack/pull/3806

This reorganizes the protos and initializes a [Buf](https://buf.build) module.

The goal here is to package protos in a more reusable way.

#### Changes

- Protos are moved under `api/ttn/lorawan/v3`. This is to create a versioned layout as is recommended with protos. The folder structure follows the (unchangeable) package name `ttn.lorawan.v3`
- Updated tooling

#### Testing

Verified generation, sample-checked diffs and checked Hugo data diff.

##### Regressions

None expected.

External developers obviously have to adapt to the new proto paths if they are currently cloning our repo and building protos themselves or importing the Swagger file.

#### Notes for Reviewers

The vendored protos are in `api/third_party`. This is to accommodate the proto generation here. This folder is excluded from what we publish to Buf Schema Registry, and we properly reference the dependencies there. That is also the reason for renaming the import paths of the dependencies.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x]  Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by pablojimpas** [comment]
Thanks for doing this @johanstokking! I thought a couple of months ago about making this proposal, but instead I chose to make these (almost exact) changes within my downstream project to reuse your Protocol Buffers. I did this primarily because it allows me to call TTN's gRPC API through an [alternative implementation](https://github.com/connectrpc/connect-go) that I already depended on, although the improvements in developer experience that Buf's compiler offers are welcome.

Will you publish these protos to the Buf Schema Registry so that others can depend on them easily? This will simplify so much my build process and the manual work of keeping the API up to date. I see a bunch of orgs in BSR (`tti`, `thethings`, `thethingsnetwork`, `thethingsindustries`), but I don't know which one is yours. [This one](https://buf.build/thethingsindustries/lorawan-stack) seems legit.

**Comment by johanstokking** [comment]
@pablojimpas thanks, glad to hear.

Pushing to the buf repository is part of a TTS release, but as the next one is only scheduled in 1,5 weeks, I just pushed the current version. See https://buf.build/thethingsnetwork/lorawan-stack.

**Comment by htdvisser** [comment]
This is really cool! Congratulations, team! 🎉

**Comment by johanstokking** [comment]
Thanks @htdvisser, this is definitely part of your legacy, and you got yourself a little green tile in on your profile 😁

**Pull request merged**
