### PR TITLE
Add responsiveness to console / oauth webui

### LINKED ISSUE #1172: Webui responsiveness
#### Summary
The web interfaces of the stack should be fully responsive. Currently, a lot of page layouts break in smaller screen sizes.

#### Why do we need this?
To enable usage of the stack's web interfaces on mobile devices. Responsiveness is a basic necessity of modern web applications.

#### What is already there? What do you see now?
Some groundwork in the code to account for responsiveness:
- stylus mixins to easily target screensizes via media queries
- definition of breakpoints
- usage of a grid system
- collapse capability of the sidebar navigation
- collapse capability of the breadcrumb container
- wireframes, defining the display logic on small screen sizes
<details>
<summary><b>Show wireframes</b></summary>

General Menu flow:
image

Tab menu in mobile versions (rendered as select component)
image

</details>

#### What is missing? What do you want to see?
More thorough integration of responsive styles in our views and components.
Additionally, we need a couple of functional extensions of our components, meaining mobile "versions" for:
- the top navigation
- side navigation
- tab navigations in general
- and likely some other components

#### Environment
All web interfaces of the stack

#### How do you propose to implement this?
I think it makes sense to treat this issue as an umbrella and follow up with multiple sub-issues.

#### Can you do this yourself and submit a Pull Request?
Yes, but this should really be a joined effort of everyone working on the web interfaces.

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
Closes #1172 

This PR will add the missing styling tweaks to the console and oauth webui, making both fully responsive.

image

#### Changes
- Add responsive styles to component
- Add responsive styles to containers
- Add responsive styles to views
- Various minor related styling tweaks

#### Notes for Reviewers
Please check all views using chromes mobile view of the chrome dev console (or even better, actual devices). Try to check both portrait and landscape as well as iPad screensizes. There are a lot of styling changes so, I'm sure some issues are to be found.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, database and configuration, according to the stability commitments in `README.md`.
- [x] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [x] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by kschiffer** [comment]
@bafonins @pgalic96 please review and focus on testing the views in the browser.

> Please check all views using chromes mobile view of the chrome dev console (or even better, actual devices). Try to check both portrait and landscape as well as iPad screensizes. There are a lot of styling changes so, I'm sure some issues are to be found.

Giving this `prio/medium` since this would be really good to have in a release before the conference.

**Comment by kschiffer** [comment]
Thanks for the thorough review.

> * Logging out from the console is failing:
> 
> ```
> Uncaught TypeError: Cannot read property 'ids' of undefined
>     at MobileMenu (index.js?8128:49)
>     at renderWithHooks (react-dom.development.js?7f13:15105)
> ```

Resolved.
> 
> * If the dropdown is long (has lots of items) like freq plans dropdown, it sometimes behaves strange depending on the position of the field on the screen, sometimes it opens up, cutting some items. It is fine with scrolling up but it might be not intuitive enough.

I think there's no good and quick way to resolve this and I think the way it works is acceptable. There might be a way to render an actual `<select />` element, which (iirc) will trigger the mobile browsers native menu. Let's look into this in a separate PR.

> * If you cannot display all breadcrumbs, focus on the last one instead of the first one, since the last one is the current view?

I know the way it works now is not optimal. Unfortunately, this cannot be done purely with CSS. I'll fix this in a separate PR as it is not an urgent issue.

> * Regarding the event container - why not restrict container a bit and let the scrolling happen anyways inside the container? That way on larger screens we could fit `pause` and `clear` buttons on the screen, and even on small screens prevent user to scroll all the way to the end of the screen to click these buttons.

Good suggestion. I'll also do this in a separate PR.

> * The box shadow in the device tabs looks strange on the screens that are wide enough that there is no scroll (check iPad), should remove it in those screens.

Fixed.

> * If you open the side navigation while gateway map is on the screen, the map will be displayed in front of the side navigation.

Fixed.

> * Maybe just put one button under the other in the `/oauth` view?
> * Also align Create account and Forgot password in the `oauth/login` view?

I don't want to touch these any further, since they'll be replaced entirely soon.

**Comment by kschiffer** [comment]
@htdvisser 
I've resolved the most important issues that @pgalic96 noted, the rest is goldplating.
I think in its current form it's good enough to merge. I'd like to do this now so we can have it included in the next release. If you're ok with that please approve, so I can hit the merge button.

**Comment by htdvisser** [comment]
I'm okay with merging the big part now, and submitting improvements later. However, I don't have time to review this now, so please chase @pgalic96 / @bafonins for that.

**Comment by bafonins** [comment]
You can see the scroll through the main navigation in the mobile view:
Screenshot 2020-01-27 at 15 17 14

Side navigation for gateways and organizations doesnt show the selected entry correctly:
Screenshot 2020-01-27 at 15 26 42
Screenshot 2020-01-27 at 15 27 06

**Comment by kschiffer** [comment]
@bafonins Thanks. I've addressed your issues.

**Pull request merged**
