### PR TITLE
Add ClassBCGatewayIdentifiers with group index

### PR DESCRIPTION
**Pull request by onizmx**
#### Summary

Reference: [#5183](https://github.com/TheThingsNetwork/lorawan-stack/issues/5183)

#### Changes

* Added ClassBCGatewayIdentifiers with group index to API for sending a downlink message to multiple gateways using the same multicast session.

#### Testing

N/A. Let me know if needed.

##### Regressions

I don't think fields prefixed with `XXX_` are used. This change won't handle values from those fields.

#### Notes for Reviewers

This change is mostly for the client side as agreed. Things I would like to get some help with are:
1. If group index validation (not_set cannot be mixed with valid group index values) should go with this PR. If yes, which places require the validation.
2. Whether validation is needed at all. I have deployed a draft version of the group index implementation, and it looks like group index without any values have 0 by default in networkserver/downlink.go. I have done something like below, and perhaps we won't need any validations as long as the implementation looks okay
```
--- a/pkg/networkserver/downlink.go
+++ b/pkg/networkserver/downlink.go
@@ -1429,22 +1429,31 @@ func (ns *NetworkServer) attemptNetworkInitiatedDataDownlink(ctx context.Context
                        QueuedApplicationUplinks: genState.appendApplicationUplinks(nil, false),
                }
        }
+       numPaths, pathsGroup := 0, make(map[uint32][]downlinkPath)
 
-       var paths []downlinkPath
        if fixedPaths := genState.ApplicationDownlink.GetClassBC().GetGateways(); len(fixedPaths) > 0 {
-               paths = make([]downlinkPath, 0, len(fixedPaths))
+               numPaths += len(fixedPaths)
                for i := range fixedPaths {
-                       paths = append(paths, downlinkPath{
+                       groupIndex := fixedPaths[i].GroupIndex
+                       pathsGroup[groupIndex] = append(pathsGroup[groupIndex], downlinkPath{
                                GatewayIdentifiers: fixedPaths[i].GatewayIds,
                                DownlinkPath: &ttnpb.DownlinkPath{
                                        Path: &ttnpb.DownlinkPath_Fixed{
-                                               Fixed: fixedPaths[i],
+                                               Fixed: &ttnpb.GatewayAntennaIdentifiers{
+                                                       GatewayIds:   fixedPaths[i].GatewayIds,
+                                                       AntennaIndex: fixedPaths[i].AntennaIndex,
+                                               },
                                        },
                                },
                        })
                }
        }
```

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by onizmx** [comment]
Hi @adriansmares. Are those chrome test failures caused by timeout? I do not see any logs pointing why they have failed.

**Comment by johanstokking** [comment]
> Hi @adriansmares. Are those chrome test failures caused by timeout? I do not see any logs pointing why they have failed.

The tests are skipped. CI is passing.

**Review by htdvisser — APPROVED** [review]
I only reviewed the API changes (because only those changes are code-owned by me).

**Comment by onizmx** [comment]
Hi @adriansmares @johanstokking Is there anything else needs to be done other than rebasing?
We have this feature running in [our production](https://github.com/halter-corp/lorawan-stack/tree/feat/halter-release-v3.18.1) for about 2 weeks and glad to know if there is anything we can do to merge this part.

**Comment by adriansmares** [comment]
Hi @onizmx ,

I have to get some time to rebase this particular PR and add the NS implementation. I don't expect too many changes from the NS changes you did for `halter-release-3.18.1`. I will keep you in the loop in case I see some serious diff between the NS implementations.

**Comment by onizmx** [comment]
@adriansmares Thank you for the explanation & brief review!

**Pull request closed without merging**
