### PR TITLE
Migrate js code checks to github actions

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Refs #2280 

#### Changes

- Migrate js code checks to github actions

#### Testing

Fork

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
See https://github.com/rvolosatovs/lorawan-stack/pull/5 for the action in action :wink:

**Comment by bafonins** [comment]
This doesnt look right
Screenshot 2020-06-16 at 11 10 00

**Comment by kschiffer** [comment]
See:
https://github.com/TheThingsNetwork/lorawan-stack/blob/05e80fb0b138af392c2d56d28fd31ddd1670d58b/.github/workflows/js.yml#L63-L67

**Comment by rvolosatovs** [comment]
> Seems to work, although we should run the mage commands in verbose mode by default, right? There's currently not enough information for failed runs due to that.

that should not be necessary - verbose mode is for debugging, we should not pollute our CI with redundant logs.
I did quite some refactoring of JS mage and JS SDK builds, I was going to push it in a separate PR, but I'll push it here, hopefully it helps with debugging.
Currently JS-related tooling does not wrap almost any errors, so naturally it's hard to debug - the errors should be wrapped with relevant details.

**Comment by rvolosatovs** [comment]
Let's merge the mage stuff first in #2751

**Comment by rvolosatovs** [comment]
CI is stuck
@johanstokking please merge

**Pull request merged**
