### PR TITLE
NS and JS component cleanup

### LINKED ISSUE #14: Clean up component registries when applications got deleted
**Summary:** 

When an application is deleted from IS, the NS and AS registries should delete the application and associated devices.

**Steps to Reproduce:** 

1. User deletes application
2. AS deletes all devices and deletes application

**What do you see now?**

Application gets deleted but devices stay there.

**What do you want to see instead?**

Devices be gone.

**How do you propose to implement this?**

An asynchronous garbage collection process in the NS and AS that deletes stale applications and its devices. This does not require an event stream, or even worse a connection, from IS to NS/AS, but rather have them be a client and check periodically if the applications are still there. This means that, as long as the garbage process has not run, unique device identifiers (i.e. JoinEUI, DevEUI) remain in the database, making it impossible to register a new device with the same identifiers.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/740 by @johanstokking

### PR DESCRIPTION
**Pull request by pgalic96**
#### Summary

Closes #14 

#### Changes

- Add `Range` to NS and JS registries
- Add `ns-db cleanup` and `js-db cleanup`

#### Testing

Manual (not sure if tests are necessary, pretty much copy paste of AS cleanup tests)

##### Regressions

New functionality

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — COMMENTED** [review]
Code-owned changes LGTM.

I do think it would be good to cover this with tests. When we decide to refactor these stores (we may migrate to a different storage backend than Redis) we want to be confident that we're not breaking anything essential.

**Review by adriansmares — APPROVED** [review]
LGTM so far. Looking forward to the tests.

**Comment by pgalic96** [comment]
Tests added. We should also probably start thinking about when/how we want to run this.

**Review by htdvisser — APPROVED** [review]
Nothing to add

**Review by adriansmares — APPROVED** [review]

**Pull request merged**
