### PR TITLE
Upgrade Go to 1.18

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

I think it's time to upgrade our module and CI to Go 1.18.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
This could be a great time to rename `interface{} ` to `any`.

I rather do it now and be consistent moving forward.

```
$ gofmt -w -r 'interface{} -> any' .
```

Should do the trick

**Comment by johanstokking** [comment]
Looks like our generated code should be excluded here. I'm fine updating the generators and making the type rename part of a follow up.

**Comment by htdvisser** [comment]
Let's not update the generators yet. I think I've reverted all changes to generated files.

**Review by adriansmares — APPROVED** [review]

**Review by nicholaspcr — APPROVED** [review]

**Review by johanstokking — APPROVED** [review]

**Comment by htdvisser** [comment]
Unfortunately this PR spent a bit more time in review than I'd hoped, and got some conflicts. To get things moving, I've removed the `interface{} -> any` rewrite, so that I can merge this without the entire team having to review. We'll do the rewrite later.

**Pull request merged**
