### PR TITLE
Update Redis library to v8

### LINKED ISSUE #2698: Update Redis library to v8
#### Summary

Update Redis library to v8

#### Why do we need this?

To remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377 and be up-to-date
Perhaps `context.Context` in all commands is also useful for us

#### What is already there? What do you see now?

v7 in #2662

#### What is missing? What do you want to see?

v8

#### How do you propose to implement this?

Update and adapt to API changes. Remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377

#### How do you propose to test this?

Integration testing

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/2698
Required by https://github.com/TheThingsNetwork/lorawan-stack/pull/3415

#### Changes

- Update Redis to v8 (out of notable changes - it now fully supports
  context cancellation and deadlines)

#### Testing

Tested in #3415

##### Regressions

There might be some unexpected side-effects from the Redis lib update

#### Notes for Reviewers

Would be nice to test this in staging and deploy as part of first proper 3.10 release.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@adriansmares @johanstokking please fix the AS test failure.
I tried, but I have no idea what might be going wrong and it's not the right time for me to dive deep into AS internal workings.

**Comment by johanstokking** [comment]
> I tried, but I have no idea what might be going wrong and it's not the right time for me to dive deep into AS internal workings.

I found the cause, working on a fix and will push here.

**Comment by johanstokking** [comment]
@rvolosatovs please take the fix from #3439

**Comment by johanstokking** [comment]
Blocked by #3439

**Comment by rvolosatovs** [comment]
It's too much effort to merge this in 3.10

**Comment by johanstokking** [comment]
> It's too much effort to merge this in 3.10

Why?

**Comment by rvolosatovs** [comment]
NS and Redis tests need to be adapted for this to be possible in 3.10
After that is done, we would have a lot of merge conflicts, because all of that functionality is changed in 3.11 (#3415 )

We can backport #3415 easily though

**Pull request closed without merging**
