### PR TITLE
Use pointers to proto messages

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This removes non-pointer usage of `Rights` and `Identifiers` proto messages.

Refs https://github.com/TheThingsIndustries/lorawan-stack/issues/3187

#### Changes

- Upgrade `protoc-gen-go-json` to fix issue with non-pointer `MarshalJSON` method
- Refactor `(*ttnpb.Rights).Sorted()`
- Move `ttnpb.XXXIdentifiers` value methods to pointer and update other components

#### Testing

Fixing compiler errors and existing tests should cover everything

##### Regressions

Maybe some things `if xxx, ok := interface{ EntityType() string }; ok { ...` stop working. Hopefully existing tests cover that...

#### Notes for Reviewers

Will submit related PR in TheThingsIndustries/lorawan-stack.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by nicholaspcr — APPROVED** [review]
lgtm but with the same note made on the Enterprise PR.

**Review by adriansmares — APPROVED** [review]

**Review by KrishnaIyer — APPROVED** [review]
Code owned packages LGTM

**Review by kschiffer — APPROVED** [review]
Codeowned LGTM.

**Review by johanstokking — APPROVED** [review]
Code owned files LGTM

**Pull request merged**
