### PR TITLE
Fix component throw persistent error

### LINKED ISSUE #1021: Fix persistent errors in entity sub views
#### Summary

Errors caused by API requests for sub entities (api keys, collaborators) persist causing the error view being shown when it shouldnt be the case.

#### Steps to Reproduce

1. Create application
2. Create application collaborator
3. Navigate to `/console/application/{app-id}/collaborators/collaborator-does-not-exist`
5. Go to the collaborators list
6. Select 

#### What do you see now?

Persistent error

#### What do you want to see instead?

The Application Collaborator Edit view without errors

 #### Environment

browser (console)

#### How do you propose to implement this?

Check for errors in `componentDidUpdate` instead of `render`. This would allow the view to dispatch the `_REQUEST` action and cleanup the errors state from previous errors.

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes #1021 

#### Changes

- Add `withRequest` hoc
- Fix application api keys pages
- Fix gateway api keys pages
- Fix application integrations page
- Fix application collaborators pages
- Fix gateway collaborators pages

#### Notes for Reviewers

~Alternative solution could be:  https://gist.github.com/bafonins/e5738ac23bb0aff2ce1e144a4c3a536a, however I am not sure if we want to introduce this hoc.~

### CODE REVIEW

**Comment by kschiffer** [comment]
> Alternative solution could be: https://gist.github.com/bafonins/e5738ac23bb0aff2ce1e144a4c3a536a, however I am not sure if we want to introduce this hoc.

I actually think the HOC solution is good. It saves us a lot of repetition and also ensures a streamlined UX for loading data and handling request errors. What are your concerns?

Also, what is the reasoning behind these lines:
https://gist.github.com/bafonins/e5738ac23bb0aff2ce1e144a4c3a536a#file-with-request-js-L24-L26

**Comment by kschiffer** [comment]
Code looks good but what about
- Gateway/Application collaborator add/edit
- Application payload formatters

?

Should we use the new HOC also for our entity pages (`views/{application|gateway|device}.js`)?

**Comment by bafonins** [comment]
> Gateway/Application collaborator add/edit

added

> Application payload formatters

what is the problem there?

> Should we use the new HOC also for our entity pages (views/{application|gateway|device}.js)?

We can

**Comment by kschiffer** [comment]
> > Application payload formatters
> 
> what is the problem there?

The view is fetching the application link, could hence also use the HOC, at least for the fetching/spinner logic.

**Comment by bafonins** [comment]
> The view is fetching the application link, could hence also use the HOC, at least for the fetching/spinner logic.

Does the view suffer from the problem described in the issue?
> Errors caused by API requests for sub entities (api keys, collaborators) persist causing the error view being shown when it shouldnt be the case.

I have no problems adding the hoc to other views that the same loading/error logic, but I would like to keep the diff as small as possible and solve only the problems listed in the issue

**Comment by kschiffer** [comment]
> Does the view suffer from the problem described in the issue?

No, but this is how we will be piling up more and more technical debt and inconsistencies. So I would prefer to either having an issue to keep track of this or to solve it right away, while we're at it.

**Comment by bafonins** [comment]
> So I would prefer to either having an issue to keep track of this or to solve it right away, while we're at it.

will create an issue

**Pull request merged**
