### PR TITLE
Do not autogenerate/prefill gateway and device ID in the console

### PR DESCRIPTION
**Pull request by PavelJankoski**
#### Summary

References #7063 

#### Changes

- Remove logic that autogenerates/prefills gateway ID.
- Remove logic that autogenerates/prefills device ID.
- Modify/update related messages.
- Update related tooltips.

##### Steps

- For gateway:
1. Login to console.
2. Navigate to gateways screen.
3. Click on register gateway.
4. Type in gateway EUI.
5. The gateway ID should not be prefilled.

- For end device:
1. Login to console.
2. Navigate to applications screen.
3. Select an application.
4. Click on register end device.
5. The gateway ID should not be prefilled.
6. Select "Enter end device specifics manually" radio button.
7. Fill in the required fields along with JoinEUI.
8. The device ID should not be prefilled.

##### Results

- For gateway:

https://github.com/TheThingsNetwork/lorawan-stack/assets/49171937/e7e7b8f5-b0c7-484e-90da-e815f915ac6a

- For end device:

https://github.com/TheThingsNetwork/lorawan-stack/assets/49171937/54892520-6c97-4503-9b55-8a1ba7ce2e33

#### Notes for Reviewers

Check the messages and tooltips if the text needs to be changed.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by KrishnaIyer** [comment]
Thanks a lot @PavelJankoski. This will really reduce the number of support requests/questions. Indeed the Tooltips need update.

#### Gateway
##### Current
Screenshot 2024-06-26 at 10 04 17

##### Proposal

`A mandatory identifier for your gateway using lowercase letters, numbers and dashes. This value must be unique per tenant and is not related to the Gateway's EUI.`

#### End Device
##### Current
Screenshot 2024-06-26 at 10 04 53

##### Proposal

`A mandatory identifier for your end device using lowercase letters, numbers and dashes. This value must be unique within an application.`

**Comment by kschiffer** [comment]
Please see my comment on the general issue here:  
[https://github.com/TheThingsNetwork/lorawan-stack/issues/7063#issuecomment-2188278874](https://github.com/TheThingsNetwork/lorawan-stack/issues/7063#issuecomment-2188278874)

I'm sorry I'm bringing this up late in the game but please let's discuss this.

**Comment by kschiffer** [comment]
Ok so concluding the discussion in #7063, we will stick with not doing any autofill.

Here's my slightly extended suggestion for the gateway tooltip.
> **What is this?**
> A mandatory identifier for your gateway that must be unique per network and cannot be changed after creation. It is used to reference your end device e.g. in events, webhooks end API requests.
> **What should I enter here?**
> Enter a value using lowercase letters, numbers, and dashes. You can choose this freely.

And the end device tooltip:
> **What is this?**
> A mandatory identifier for your end device that must be unique within the application and cannot be changed after creation. It is used to reference your end device e.g. in events, webhooks end API requests.
> **What should I enter here?**
> Enter a value using lowercase letters, numbers, and dashes. You can choose this freely.

**Review by kschiffer — CHANGES_REQUESTED** [review]
See above.

**Review by kschiffer — APPROVED** [review]
End to end tests need an update here as well.

**Pull request merged**
