### PR TITLE
Fix `ttn-lw-cli simulate` flag casing

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Partial fix for https://github.com/TheThingsNetwork/lorawan-stack/issues/6028

#### Changes

- Fixes `lorawan-version` and `lorawan-phy-version` flag casing

#### Testing

Local testing

##### Regressions

None, this is the old behavior

#### Notes for Reviewers

This can be merged as-is, but the `simulate` command is still not functional. See the referenced issue. @ysmilda you can take over this PR and push commits to this branch or open a new PR, up to you.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by ysmilda** [comment]
I've moved the proto definitions to the `api` folder and after regenerating everything the commands seemed to work as expected. @johanstokking Could you test it again with this branch?

**Comment by johanstokking** [comment]
How did you test?

It seems that the EUIs still need to be passed as base64, right?

This is an example command that works on 3.22 branch:

```bash
$ ttn-lw-cli simulate gateway-join-request --gateway-id simulation \
  --dev-eui 1122334455667788 \
  --join-eui EC656E0000000000 \
  --lorawan-version 1.0.2 \
  --app-key 11223344556677881122334455667788 \
  --lorawan-phy-version 1.0.2-b \
  --band-id EU_863_870 \
  --dev-nonce 0015
```

Note that `--app-key` used to be just hex, now it's a key envelope.

**Comment by ysmilda** [comment]
I didn't have my cli setup with authentication and it was erroring out on that. I wrongly assumed that all parsing had already finished by then.

**Comment by ysmilda** [comment]
@johanstokking The issue we saw here was caused by improper normalisation and invalid validation. Could you verify that the command can now be run succesfully?

**Comment by johanstokking** [comment]
> Note that `--app-key` used to be just hex, now it's a key envelope.

The command fails because of the above.

**Comment by ysmilda** [comment]
The app-key field has been reverted to a hex input so that the original commands work as is. When testing here locally it works with the command you've shown above.
```
go run ./cmd/ttn-lw-cli/main.go simulate gateway-join-request --gateway-id simulation \
  --dev-eui 1122334455667788 \
  --join-eui EC656E0000000000 \
  --lorawan-version 1.0.2 \
  --app-key 11223344556677881122334455667788 \
  --lorawan-phy-version 1.0.2-b \
  --band-id EU_863_870 \
  --dev-nonce 0015
```

**Review by ysmilda — APPROVED** [review]
LGTM

**Comment by johanstokking** [comment]
Tested and verified it works

**Review by adriansmares — APPROVED** [review]

**Pull request merged**
