### PR TITLE
Backport gateway claiming

### PR DESCRIPTION
**Pull request by PavelJankoski**
#### Summary

Backport gateway claiming.

### CODE REVIEW

**Comment by johanstokking** [comment]
@KrishnaIyer The Console was always setting `cups_redirection`. This is now a deprecated field and so I removed it. Please acknowledge that won't have any downsides.

The reason this came up is that I'm running TTS in http locally, so the URI started with `http` not `https` which failed validation.

**Comment by KrishnaIyer** [comment]
> The Console was always setting cups_redirection. This is now a deprecated field and so I removed it. Please acknowledge that won't have any downsides.

ACK. 

The legacy claimer will use the `target_gateway_server_address` field to fetch the CUPS trust. That has to be an HTTPS endpoint (which it is for production). This does not happen for other upstreams and this is safe to do.

**Review by johanstokking — APPROVED** [review]

**Review by kschiffer — APPROVED** [review]

**Review by johanstokking — CHANGES_REQUESTED** [review]
I did some integration testing and it looks like the gateway is not unclaimed when it gets deleted.

Gateways must be unclaimed on delete. This is similar to end devices that are unclaimed on a Join Server when they are deleted in The Things Stack:

Screenshot 2024-07-31 at 14 31 25

This is basically calling the `Unclaim` rpc of DCS.

We never did this for The Things Indoor Gateway because anyone with the owner token can claim the gateway, even if the claim is held by someone else. We're changing course and for that the gateway needs to be unclaimed on delete.

**Review by johanstokking — APPROVED** [review]
Pushed a small fix. We never used this code path.

**Pull request merged**
