### PR TITLE
Fix/stdin pipe read error

### LINKED ISSUE #2545: Creating devices by passing JSON to CLI stdin does not work
#### Summary

Creating devices by passing JSON to CLI stdin does not work

#### Steps to Reproduce

1. Pipe a valid device JSON to `ttn-lw-cli device create`

#### What do you see now?

```shell
$ cat dev.json
{
  "ids": {
    "device_id": "test-dev",
    "application_ids": {
      "application_id": "test-app"
    },
    "dev_eui": "0102030405060708",
    "join_eui": "0807060504030201"
  },
  "frequency_plan_id": "US_902_928_FSB_2",
  "lorawan_version": "1.0.2",
  "lorawan_phy_version": "1.0.2-b"
}
$ cat dev.json | ttn-lw-cli device create
 DEBUG Using access token (valid until 11:35AM)
error:cmd/ttn-lw-cli/commands:no_application_id (no application ID set)
$ cat dev.json | ttn-lw-cli device create --application-id 'test-app'
 DEBUG Using access token (valid until 11:35AM)
error:cmd/ttn-lw-cli/commands:no_end_device_id (no end device ID set)
$ cat dev.json | ttn-lw-cli device create --application-id 'test-app' --device-id 'test-dev'
 DEBUG Using access token (valid until 11:35AM)
error:cmd/ttn-lw-cli/commands:no_end_device_eui (no end device EUIs set)
$ cat dev.json | tr -d '\n' | ttn-lw-cli device create --application-id 'test-app' --device-id 'test-dev'
 DEBUG Using access token (valid until 11:35AM)
error:cmd/ttn-lw-cli/commands:no_end_device_eui (no end device EUIs set)
```

as you see I also tested if this be to some weird whitespace issues in the last invocation, but that did not help.

#### What do you want to see instead?

Successful `<json> | ttn-lw-cli end-device create`

#### Environment

3.8.1

#### How do you propose to implement this?

Actually read the stdin

#### Can you do this yourself and submit a Pull Request?

yes, but I'll assign @neoaggelos since he worked on this

### PR DESCRIPTION
**Pull request by neoaggelos**
#### Summary

Closes #2545 

#### Changes

- Use a buffered reader and peak for input in order to decide whether stdin is available
- Use that buffered reader for further input (since the original reader has consumed the first byte of input)

#### Testing

```bash
$ cat file.json | ttn-lw-cli ... create        # works
$ ttn-lw-cli ..... create < file.json           # works
$ (create without tty as show in #1904)  # works
```

##### Regressions

It could be possible that since we may drop the first byte from `os.Stdin` with this, other CLI commands that expect user input might break. Tested user create (ttn-lw-cli user create), login, login with callback=false (where we need to enter the oauth token from stdin) and they worked OK. Also updated the device claiming commands (which also used IsPipe())

#### Notes for Reviewers

- Skipping the proposed check for `{` and `[`, since it breaks with whitespace. The decoder itself will fail if the input is in fact invalid.
- Returning the buffered reader is needed, otherwise we drop the first byte of the input

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [X] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by htdvisser** [comment]
Can you please also test that everything still works as expected in the "normal" case?

Did you test this on both macOS and Linux? In the experiment for [my suggestion](https://github.com/TheThingsNetwork/lorawan-stack/issues/2545#issuecomment-644604095) I got different results on macOS and Linux.

**Comment by neoaggelos** [comment]
> Can you please also test that everything still works as expected in the "normal" case?

Tested that as well

> Did you test this on both macOS and Linux? In the experiment for [my suggestion](https://github.com/TheThingsNetwork/lorawan-stack/issues/2545#issuecomment-644604095) I got different results on macOS and Linux.

This should be about the shell, not the OS. Unfortunately, I cannot test on macOS.

**Comment by linekermtl** [comment]
Same issue as https://github.com/TheThingsNetwork/lorawan-stack/issues/2545, on macOS:

$ ttn-lw-cli version
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.8.6
Build date:          2020-07-10T12:23:39Z
Git commit:          47abc33b5
Go version:          go1.14.4
OS/Arch:             darwin/amd64

$ cat template.json | ttn-lw-cli device create --application-id test-lab --device-id 'testdevice-1'
error:cmd/ttn-lw-cli/commands:no_end_device_eui (no end device EUIs set)

**Comment by neoaggelos** [comment]
@linekermtl Can you include the shell you are using and the `template.json` file? You can strip away any sensitive data.

Can you also try with `ttn-lw-cli device create --application-id test-lab --device-id testdevice-1 < template.json`?

**Comment by linekermtl** [comment]
$ echo $SHELL
/bin/bash
$ cat template.json
{
  "end_device": {
      "ids": {
	"application_ids": {
	  "application_id": "xxxxx"
      },
	"dev_eui": "xxxxx",
	"join_eui": "xxxxx"
    },
    "created_at": "0001-01-01T00:00:00Z",
    "updated_at": "0001-01-01T00:00:00Z",
    "attributes": {
    },
    "version_ids": {
      "brand_id": "xxxxx",
      "model_id": "xxxxx",
      "firmware_version": "xxxxx"
    },
    "network_server_address": "xxxxx",
    "lorawan_version": "1.0.2",
    "lorawan_phy_version": "1.0.2-b",
    "frequency_plan_id": "US_902_928_FSB_2",
    "supports_join": true
  },
  "field_mask": {
    "paths": [
      "version_ids.firmware_version",
      "version_ids.model_id",
      "frequency_plan_id",
      "lorawan_phy_version",
      "lorawan_version",
      "supports_class_c",
      "supports_join",
      "version_ids.brand_id"
    ]
  }
}
$ ttn-lw-cli device create --application-id xxxxx --device-id xxxxx < template.json
error:cmd/ttn-lw-cli/commands:no_end_device_eui (no end device EUIs set)

@neoaggelos I've also tried the command without --application-id or --device-id, same error message.

**Comment by neoaggelos** [comment]
@linekermtl Based on the template.json file you attached, I think the error is that the template file is used incorrectly. As shown in the [documentation for executing the end-device templates](https://thethingsstack.io/v3.8.6/devices/end-device-templates/executing/), the correct command is:

```bash
$ cat template.json \
  | ttn-lw-cli end-device template assign-euis <join-eui> <dev-eui> \
  | ttn-lw-cli end-device template execute \
  | ttn-lw-cli device create --application-id <application-id>
```

Also, how did you create this template? The template itself should not really contain the DevEUI.

**Comment by rvolosatovs** [comment]
Let's continue discussion in the issue: https://github.com/TheThingsNetwork/lorawan-stack/issues/2545

**Pull request merged**
