### PR TITLE
Various improvements related to Redis task queues

### LINKED ISSUE #2698: Update Redis library to v8
#### Summary

Update Redis library to v8

#### Why do we need this?

To remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377 and be up-to-date
Perhaps `context.Context` in all commands is also useful for us

#### What is already there? What do you see now?

v7 in #2662

#### What is missing? What do you want to see?

v8

#### How do you propose to implement this?

Update and adapt to API changes. Remove https://github.com/TheThingsNetwork/lorawan-stack/pull/2662#discussion_r438065377

#### How do you propose to test this?

Integration testing

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/2698
Required by https://github.com/TheThingsNetwork/lorawan-stack/pull/3398

#### Changes

- Update Redis to v8 (out of notable changes - it now fully supports
  context cancellation and deadlines) ~(#3438 )~
- Make Redis task dispatch lazy and consumer-initiated, i.e. when the work
  queues are empty, one of the consumers performs the dispatch of tasks.
  This ensures correctness, and simplifies scaling as well as
  implementation. Under very heavy load this could potentially lead to bad
  performance, since then pop/dispatch script could task a long time to
  execute. As previously mentioned by @adriansmares, we should
  investigate designating separate Redis instances to different
  components/features to mitigate this if it ever becomes a problem.
- Clean-up Network Server downlink tasks

#### Testing

Unit tests, integration testing

##### Regressions

Potentially downlink tasks could break, but I am performing extensive
testing to avoid that
Aditionally, there might be some unexpected side-effects from the Redis
lib update

#### Notes for Reviewers

~Would be nice to test this in staging and deploy as part of first proper 3.10 release.~

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
I don't see obvious mistakes, but needs review from @adriansmares on the Lua bits. Also I'd strongly prefer targeting 3.11 for this one.

**Review by kschiffer — APPROVED** [review]
Codeowned files LGTM!

**Comment by rvolosatovs** [comment]
I'm consistently getting these 2 test failures in CI, so it does not seem like a flake:
```
--- FAIL: TestApplicationServer (51.62s)
    --- FAIL: TestApplicationServer/Traffic/webhooks (4.67s)
        --- FAIL: TestApplicationServer/Traffic/webhooks/Downstream (0.52s)
            --- FAIL: TestApplicationServer/Traffic/webhooks/Downstream/UnregisteredDevice/Push (0.51s)
                applicationserver_test.go:1996: Expected upstream event
FAIL
coverage: 58.5% of statements
FAIL	go.thethings.network/lorawan-stack/v3/pkg/applicationserver	51.804s
```

```
 --- FAIL: TestGatewayServer (6.21s)
    --- FAIL: TestGatewayServer/Traffic/grpc (0.51s)
        doc.go:66: 
            /home/runner/work/lorawan-stack/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:695
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/grpc/NotConnected (0.00s)
            gatewayserver_test.go:696: Expected gateway not to be connected yet, but it is
FAIL
coverage: 42.5% of statements
FAIL	go.thethings.network/lorawan-stack/v3/pkg/gatewayserver	6.250s
```

@johanstokking can you take a look?

**Comment by johanstokking** [comment]
@rvolosatovs I thought these were flakes too, so I increased the timeouts and pushed to your branches, but I reverted that after looking at the debug output;

```
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51222 request_id=01EP42RVZY92MFDVHXSPMK5DGB test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver:new_connection (new connection from same gateway) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51227 request_id=01EP42RW19FT4SB0QKRBA82NXJ test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context deadline exceeded) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51228 request_id=01EP42RW2F28PP7KPCE8XWQW4R test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51230 request_id=01EP42RWARR21TBT4VFJTK2A6W test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51231 request_id=01EP42RWBWBMBM4PWFX66RP42E test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51232 request_id=01EP42RWCZ993MG0DS8A89W9DF test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51233 request_id=01EP42RWE34CFG6HD9Q93SVAZH test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:unknown:unknown (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51234 request_id=01EP42RWEA328BWCEXCJ2ATPRF test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 grpc_method=LinkGateway grpc_service=ttn.lorawan.v3.GtwGs namespace=gatewayserver/io/grpc protocol=grpc remote_addr=127.0.0.1:51235 request_id=01EP42RWFDD3R5HAE0V4B94C6A test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51236 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver:new_connection (new connection from same gateway) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51241 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51242 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51244 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51245 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51246 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51247 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51248 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/errors:context_canceled (context canceled) gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/mqtt protocol=mqtt remote_addr=127.0.0.1:51251 test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver/io/udp:connection_expired (connection expired) gateway_eui=AAEE000000000000 gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/udp protocol=udp test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver/io/udp:connection_expired (connection expired) gateway_eui=BBFF000000000000 gateway_uid=eui-bbff000000000000 namespace=gatewayserver/io/udp protocol=udp test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver/io/udp:connection_expired (connection expired) gateway_eui=AAEE000000000000 gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/udp protocol=udp test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver/io/udp:connection_expired (connection expired) gateway_eui=AAEE000000000000 gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/udp protocol=udp test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver/io/udp:connection_expired (connection expired) gateway_eui=AAEE000000000000 gateway_uid=eui-aaee000000000000 namespace=gatewayserver/io/udp protocol=udp test_name=TestGatewayServer
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51253 request_id=01EP42S12K1AY227V7ZPKBTXCC test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51254 request_id=01EP42S12NRRMWAMH91A296ZP8 test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/gatewayserver:new_connection (new connection from same gateway) gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51257 request_id=01EP42S13RPHPMYRDPJWF7B13K test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51258 request_id=01EP42S14RNM9HQ780CM8ZR7D1 test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51260 request_id=01EP42S1D5GXWXBGB39NKGBV35 test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51261 request_id=01EP42S1D858MEKRNJ76YREP8P test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
 ERROR Failed to delete connection stats        error=error:pkg/redis:store (store error) error_cause=websocket: close 1006 (abnormal closure): unexpected EOF gateway_uid=eui-aaee000000000000 method=GET namespace=gatewayserver/io/ws protocol=ws remote_addr=127.0.0.1:51264 request_id=01EP42S1EBAJ556Q04V0ARAVKQ test_name=TestGatewayServer url=/traffic/eui-aaee000000000000
--- FAIL: TestGatewayServer (6.38s)
    --- FAIL: TestGatewayServer/Traffic/grpc (0.87s)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:695
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/grpc/NotConnected (0.00s)
            gatewayserver_test.go:696: Expected gateway not to be connected yet (<nil>)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:1539
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/grpc/Disconnected (0.00s)
            gatewayserver_test.go:1540: Expected gateway to be disconnected, but it's not
    --- FAIL: TestGatewayServer/Traffic/mqtt (0.84s)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:695
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/mqtt/NotConnected (0.00s)
            gatewayserver_test.go:696: Expected gateway not to be connected yet (<nil>)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:1539
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/mqtt/Disconnected (0.00s)
            gatewayserver_test.go:1540: Expected gateway to be disconnected, but it's not
    --- FAIL: TestGatewayServer/Traffic/udp (1.87s)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:695
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/udp/NotConnected (0.00s)
            gatewayserver_test.go:696: Expected gateway not to be connected yet (<nil>)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:1539
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/udp/Disconnected (0.00s)
            gatewayserver_test.go:1540: Expected gateway to be disconnected, but it's not
    --- FAIL: TestGatewayServer/Traffic/basicstation (0.75s)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:695
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/basicstation/NotConnected (0.00s)
            gatewayserver_test.go:696: Expected gateway not to be connected yet (<nil>)
        doc.go:66: 
            /Users/johan/dev/src/lorawan-stack/pkg/gatewayserver/gatewayserver_test.go:1539
            Expected: true
            Actual:   false
        --- FAIL: TestGatewayServer/Traffic/basicstation/Disconnected (0.00s)
            gatewayserver_test.go:1540: Expected gateway to be disconnected, but it's not
FAIL
exit status 1
FAIL    go.thethings.network/lorawan-stack/v3/pkg/gatewayserver 6.741s
```

The issue here is that the gateway stats cannot be deleted because the context is canceled. This means effectively that the gateway stays connected, therefore failing subsequent tasks. This context-aware Redis is introduced in this branch.

I can give further advice on this if you need to, let me know, but best is to test locally for speed and consistency, before seeing if CI works or not.

**Comment by rvolosatovs** [comment]
Setting `prio/medium`, since this is required for critical part of roadmap

**Comment by rvolosatovs** [comment]
@johanstokking as I said above, these did not look like flakes and so I asked you to fix the tests, since you are more familiar with the affected components. I will take over this myself.

**Comment by johanstokking** [comment]
You asked whether I could take a look, and I did that. If you need me to adapt the code to a canceled context, I can do that or advice on that but please be clear in what you ask. 

It is by design that gateway stats are deleted on disconnect, which is triggered by or causes a context cancellation. So I think that you should use the component context for this.

**Comment by rvolosatovs** [comment]
Blocked by #3438

**Comment by johanstokking** [comment]
```diff
diff --git a/pkg/gatewayserver/gatewayserver.go b/pkg/gatewayserver/gatewayserver.go
index 8de303205..3fb3efb03 100644
--- a/pkg/gatewayserver/gatewayserver.go
+++ b/pkg/gatewayserver/gatewayserver.go
@@ -951,5 +951,5 @@ func (gs *GatewayServer) UpdateConnectionStats(conn *io.Connection) error {
 
 // ClearConnectionStats clears the connection stats for a gateway.
 func (gs *GatewayServer) ClearConnectionStats(conn *io.Connection) error {
-	return gs.statsRegistry.Set(conn.Context(), conn.Gateway().GatewayIdentifiers, nil)
+	return gs.statsRegistry.Set(gs.Context(), conn.Gateway().GatewayIdentifiers, nil)
 }
```

**Comment by rvolosatovs** [comment]
blocked by https://github.com/TheThingsNetwork/lorawan-stack/pull/3440

**Review by adriansmares — APPROVED** [review]

**Comment by adriansmares** [comment]
Lua and the rest of the PR LGTM  👍 .

**Comment by rvolosatovs** [comment]
@johanstokking still need your approval for merge

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
