### PR TITLE
Make application-layer f_port check stricter

### LINKED ISSUE #692: Check FPort on downlink
#### Summary

Check the `FPort` on scheduled downlink.

#### Why do we need this?

To fail downlinks with invalid ports.

#### What is already there? What do you see now?

No check.

#### What is missing? What do you want to see?

- Add API validation so that NS rejects `FPort=0`
- Fail downlinks on reserved `FPort` (`224`)
- Fallback to `FPort=1` when its `0`

#### How do you propose to implement this?

- Set validation minimum value of `1` for `f_port` in `ApplicationDownlink`
- Check validity of `FPort` in downlink operation
- Extend cleaning downlinks by setting default value

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Closes #692

#### Changes

Turns out that #692 can be closed simply with validation

### CODE REVIEW

**Comment by johanstokking** [comment]
Looks like our generated documentation and JS SDK definition doesn't handle `not_in`

**Comment by htdvisser** [comment]
I'll see what's up with that `not_in` in the documentation.

**Comment by htdvisser** [comment]
FYI: That documentation for `not_in` should be fixed with https://github.com/pseudomuto/protoc-gen-doc/pull/392

**Comment by rvolosatovs** [comment]
I'll update protoc image once it's merged and a new version is released!

**Pull request merged**
