### PR TITLE
dev: Replace satori/go.uuid with google/uuid

### LINKED ISSUE #6448: Remove extra uuid dependency
### Summary

We currently have two packages used for generating universally unique identifiers (UUIDs), them being `github.com/satori/go.uuid` and `github.com/google/uuid`. 

It would be nice to do the small cleanup and just use one of them. Both are based on the same specifications RFC 4122 and their usage revolves mostly around tests, but there are two non test cases in which they are used: 
1. The CLI's telemetry `uid`
2. In the error's correlationID during its `build` procedure. 

### Current Situation

Use of both packages alternating between tests, error pkg and telemetry pkg

### Desired Situation

All these packages should use only of the two uuid and the other should be removed from the dependency list.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by Juneezee**
#### Summary

Closes #6448.

#### Changes

Replaces `github.com/satori/go.uuid` with `github.com/google/uuid`.

#### Testing

```
 ./tools/bin/mage go:test
```

##### Regressions

None

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks @Juneezee and happy new year!

**Review by nicholaspcr — APPROVED** [review]
Looks good to me.
Thank you @Juneezee for the contribution!

**Comment by nicholaspcr** [comment]
@johanstokking I don't have permission to merge without your approval. 
Just as an extra note I double checked and both dependencies have their implementations based on [RFC4122](https://datatracker.ietf.org/doc/html/rfc4122) and the google's uuid methods called in this PR use the `version 4` which is what we were using.

**Review by johanstokking — APPROVED** [review]
Looks good to me too. @nicholaspcr thanks for verifying it's using V4 by default, that was my only question.

**Comment by johanstokking** [comment]
It looks like our end-to-end tests are hitting the 15 minute timeouts and that is the reason they fail. I don't think there's a relation with this PR, so I'm merging.

**Pull request merged**
