### PR TITLE
Release 3.8.4

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Release 3.8.4

### CODE REVIEW

**Comment by rvolosatovs** [comment]
@johanstokking please merge

**Comment by rvolosatovs** [comment]
Blocked by #2711

**Comment by johanstokking** [comment]
Blocked reference is closed; I rebased on 60ec85471d16c8d8c8ab8da920d018318026b288

Anything else?

**Comment by rvolosatovs** [comment]
> Blocked reference is closed; I rebased on [60ec854](https://github.com/TheThingsNetwork/lorawan-stack/commit/60ec85471d16c8d8c8ab8da920d018318026b288)
> 
> Anything else?

no, please merge

**Pull request merged**
