### PR TITLE
Allow admins to choose between soft/hard entity deletion in the Console

### LINKED ISSUE #3585: Allow restoring and purging soft-deleted entities in the Console
#### Summary

With https://github.com/TheThingsNetwork/lorawan-stack/pull/3467 we allow deleting entities and releasing their ids. We should add this to the Console.

#### Why do we need this?

Allow the user to chose between soft and hard deletion.

#### What is already there? What do you see now?

Delete modal
Screenshot 2020-12-10 at 16 48 14

that uses `Delete` RPC's for each entity.

#### What is missing? What do you want to see?

Option to perform hard deletion.

#### Environment

v3.10.4

#### How do you propose to implement this?

IMO, we can extend the existing modal with `Release entity ID` checkbox that initially is unchecked.
cc @kschiffer 

#### How do you propose to test this?

e2e tests and manual testing

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by bafonins**
#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/3585

<details>
<summary>Screenshot</summary>

Screenshot 2021-07-28 at 14 57 53
Screenshot 2021-07-28 at 14 57 59
Screenshot 2021-07-28 at 14 55 29
Screenshot 2021-07-28 at 14 55 24
Screenshot 2021-07-28 at 14 55 15
Screenshot 2021-07-28 at 14 55 04
Screenshot 2021-07-28 at 14 54 56

</details>

#### Changes

- Allow admins to choose between hard and soft deletion of an entity

#### Testing

Manual

#### Notes for Reviewers

Went with another solution to toggle between hard and soft deletion than described by @kschiffer  in https://github.com/TheThingsNetwork/lorawan-stack/issues/3585#issuecomment-867664544 to avoid responsiveness issues. 

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by pgalic96 — APPROVED** [review]

**Comment by kschiffer** [comment]
What was the conclusion of this?

**Comment by bafonins** [comment]
@kschiffer After discussing it with @htdvisser we decided to close this PR and look for another solution. Here is some context:

> For background: the idea behind the "purge" feature was that it could be used by admins to permanently delete entities that were already soft-deleted. It was never intended to be a normal flow and definitely not the default for admins

**Comment by bafonins** [comment]
Updated PR and screenshots, cc @kschiffer

**Review by kschiffer — APPROVED** [review]
LGTM but please change the order of messages a bit:

1.  `Are you sure you want to delete`
2.  Implications message `This will permanently delete…`
3.  Entity purge checkbox
4.  Entity purge warning (if checkbox is checked)
5.  Type to confirm

**Pull request merged**
