### PR TITLE
Initial Network Server flow test

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Refs #176 

#### Changes

- Added a simplistic Class A OTAA flow test for EU868 device

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Blocked by #652 #655

**Comment by johanstokking** [comment]
@rvolosatovs please rebase for review

**Comment by rvolosatovs** [comment]
@johanstokking done

**Comment by rvolosatovs** [comment]
I improved it a bit. Further generalizations should be done in when we actually work on #176

**Comment by rvolosatovs** [comment]
Yes!

**Pull request merged**
