### PR TITLE
Fix NS panic when RX2 parameters cannot be computed

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack/issues/2360

#### Changes

- Fix NS panic when RX2 parameters cannot be computed

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by adriansmares — APPROVED** [review]
So the `rx2DR` was `nil` due the invalid data rate index, which lead to the nil `maxDR` which caused the panic ?

**Comment by rvolosatovs** [comment]
> So the `rx2DR` was `nil` due the invalid data rate index, which lead to the nil `maxDR` which caused the panic ?

Exactly.

Regarding the RX1 DR question, which you since removed - we'd return on https://github.com/TheThingsNetwork/lorawan-stack/blob/96ca2a2ee7f41b071f94db61a5b4f78be77e6723/pkg/networkserver/downlink.go#L1076-L1085, but I guess you already figured it out

**Comment by johanstokking** [comment]
This doesn't fully close https://github.com/TheThingsIndustries/lorawan-stack/issues/2360, as it doesn't recover panics. Is there a reason not to recover panics if something fails because of some edge case? cc @htdvisser

**Comment by rvolosatovs** [comment]
The panics should not happen. `panic` == execution cannot continue and the only sensible option is to fail. Everything else should be handled as errors.

FTR, if NS would recover here, it'd end up in an infinite loop and we don't want that.

**Comment by johanstokking** [comment]
> The panics should not happen. `panic` == execution cannot continue and the only sensible option is to fail.

"execution" is scoped to handling the uplink message, and "to fail" is to drop the uplink message. That can be achieved by recovering the panic and logging it so we can fix it. But it doesn't unnecessarily take down the entire Network Server and throws away everything that was in progress.

**Comment by rvolosatovs** [comment]
So if we're talking about recovering from bugs in this particular case - sure, the downlink task can be wrapped in a `recover` block, just like we do with RPCs. It makes a lot of sense to do that, since the panic then is specific to the device. But we should add a recover to the whole NS itself.

**Comment by htdvisser** [comment]
You can't `recover` from uncaught panics in another goroutine, but I think it would be good if we could recover in some scoped/isolated places. We already have recovery in an uplink RPC (as gRPC middleware), so this would be about recovering the downlink task. Perhaps it would even make sense to build it into `pkg/component/tasks.go` directly, so that it applies to any background task.

**Comment by rvolosatovs** [comment]
> You can't `recover` from uncaught panics in another goroutine, but I think it would be good if we could recover in some scoped/isolated places. We already have recovery in an uplink RPC (as gRPC middleware), so this would be about recovering the downlink task. Perhaps it would even make sense to build it into `pkg/component/tasks.go` directly, so that it applies to any background task.

Yep, that's exactly what I did in https://github.com/TheThingsNetwork/lorawan-stack/pull/3264

**Pull request merged**
