### PR TITLE
Release `v3.31.1`

### PR DESCRIPTION
**Pull request by happyRip**
This pull request merges back changes from the v3.31.1 release.

#### Notes for Reviewers

Should it merge into `v3.32` or `v3.31` and then rebase `v3.32`?

### CODE REVIEW

**Comment by johanstokking** [comment]
> Should it merge into `v3.32` or `v3.31` and then rebase `v3.32`?

What should be merged in `v3.31` is the changelog cut-off and the versions in `package.json` etc.

Then we should merge `v3.31` into `v3.32` because we can't rebase `v3.32` because we can't force-push because it's a protected branch.

**Comment by KrishnaIyer** [comment]
Why is there a functional diff here in the first place? Afaik we always merge changes (after the merge deadline) to the target branch and only backport relevant fixes via cherry picking.
In my understanding, only the bump version commit including the changelog is brought back into the target branch.

**Comment by happyRip** [comment]
The 2 commits in the middle are already in the `v3.31` branch. Maybe the last commit confused the diff algorithm. I checked the files manually and they are already with the changes we see here.

**Comment by johanstokking** [comment]
The reason that these commits are there is that this branch wasn't rebased on the target branch, I fixed that here for clarity.

**Comment by johanstokking** [comment]
Sorry I now see https://github.com/TheThingsNetwork/lorawan-stack/pull/7215. That PR replaces this one right?

**Comment by happyRip** [comment]
Yes

**Pull request closed without merging**
