### PR TITLE
Remove "could not" and "failed to" from error messages

### LINKED ISSUE #6469: Remove "could not" and "failed to" from error messages
### Summary

Remove "could not" and "failed to" from error messages. An error message implies that an action could not be completed or it failed.

We have a list of legacy errors that still have these and let's remove these and make @johanstokking happy.

### Current Situation

There's a collection of older error definitions that start with `could not` or `failed to`.
Examples
```go
errEndDeviceClaimInfo = errors.DefineFailedPrecondition(
"end_device_claim_info",
"could not get end device claim info from DCS",
)
errPkgDataMerge     = errors.DefineCorruption("pkg_data_merge", "failed to merge package data")
``` 

### Why do we need this? Who uses it, and when?

To make the codebase consistent.

### Proposed Implementation

1. Do a search in `*.go` files for `could not` and `failed to`. You can also check `config/messages.json`.
2. If the message is part of an error definition ex: `errXYZ = errors.DefineXYZ ("xxx", "could not --")` remove these words and.
3. Update the error messages to make grammatical sense. Ex; `could not connect to Join Server` -> `connect join server`. Since this text is part of an error message, it's grammar make sense.
4. You don't need to update items that are `logger.Warn()` since those log statements are meant for a different purpose.
5. Regenerate messages `tools/bin/mage go:messages.`
6. Repeat for enterprise.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by happyRip**
#### Summary

Closes #6469 

#### Changes

- Remove "could not" and "failed to" from error messages

#### Testing

CI

##### Regressions

n/a

#### Notes for Reviewers

To find files with error definitions containing "could not" and "failed to" I've created a simple script:
```bash
jq -r <config/messages.json \
  '.[]
  | select(
    .translations.en
    | contains("could not") or contains("failed to")
  )
  | .description
  | "\(.package)/\(.file)"' \
| sort -u
```
 
#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by kschiffer — APPROVED** [review]
Codeowned LGTM

**Review by adriansmares — APPROVED** [review]
LGTM. Please don't forget to follow up with an Enterprise variant of this, for the errors there.

**Review by johanstokking — APPROVED** [review]
Awesome

**Review by nicholaspcr — APPROVED** [review]

**Review by KrishnaIyer — APPROVED** [review]
Great!

**Pull request merged**
