### PR TITLE
as: Sync normalized payload data model and validation to the latest schema

### PR DESCRIPTION
**Pull request by pablojimpas**
#### Summary

References https://github.com/TheThingsNetwork/lorawan-devices/issues/395

While [responding to a TTN forum thread](https://www.thethingsnetwork.org/forum/t/sensecap-s2120-8-in-1-payload-edit/62487/2?u=pablojimpas), I've discovered that the current version of TTS does not support all the normalized payload properties that are present in the schema at this moment. This PR updates the data model and the validation code in TTS to keep in sync with the [current JSON schema](https://github.com/TheThingsNetwork/lorawan-devices/blob/cbc0876cf3b5a2b888b40568ff9c41a8726a1fbd/lib/payload.json).

#### Changes

- Add `CO2` and `LightIntensity` properties to the `Air` object.
- Add `Soil` object with all of its properties.

#### Testing

- Unit tests

##### Regressions

- None

#### Notes for Reviewers

- Be aware that keeping the schema in sync with the code it's a very repetitive task, so be on the hunt for potential bugs. In the latest commit 92baeb391e86f0c86adca35dd757af86a018da82 I've started abstracting some validation logic into separate functions to avoid potential mismatches in the future, please let me know if you like this approach.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]
Great, thanks

**Comment by johanstokking** [comment]
CI is broken, will make sure this lands in 3.25.2.

**Comment by johanstokking** [comment]
@pablojimpas can you rebase on latest `v3.25` branch? CI should work again

**Comment by pablojimpas** [comment]
> @pablojimpas can you rebase on latest `v3.25` branch? CI should work again

Done! Let's see if it works now.

**Comment by adriansmares** [comment]
I am not sure if the rebase was entirely correct - I would've have expected to see only your original 3 commits. Could you try to `reset --hard` on top of the latest `v3.25` and then cherry pick 1dc5430321bdc9131ce038372bdafae85fcce6a7 , a72038eb6fb7f4f9d3d33ec21ff41c35db2e2f85 and 92baeb391e86f0c86adca35dd757af86a018da82 ?

Edit: Seems the syntax is not ok anyway https://github.com/TheThingsNetwork/lorawan-stack/actions/runs/4700691397/workflow . I will check again.

**Comment by pablojimpas** [comment]
Sorry @adriansmares, it's fixed now. I will rebase again once the CI issue is solved.

**Comment by adriansmares** [comment]
> Sorry @adriansmares, it's fixed now. I will rebase again once the CI issue is solved.

Great ! I have merged https://github.com/TheThingsNetwork/lorawan-stack/pull/6156 - let's see if CI is happier now, after you rebase again.

**Pull request merged**
