### PR TITLE
doc: Add command to start The Things Stack

### LINKED ISSUE #2486: Development Document Update
Summary

Add `go run ./cmd/ttn-lw-stack start` to start The Things Stack

Why do we need this ?

In the presence of this command, the user of this repository will be able to start The Things Stack without any assistance

What is already there? What do you see now?

Currently, the user is only able to start The Things Stack by asking for some assistance

What is missing? What do you want to see?

Currently, "go run ./cmd/ttn-lw-stack start" is missing in the DEVELOPMENT.md document. I would like to see "go run ./cmd/ttn-lw-stack start" in the document so that the user of this repository can start The Things Stack without any hassle

How do you propose to document this?

By adding "go run ./cmd/ttn-lw-stack start" in the newly created "Starting The Things Stack" section

Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by jatinssaluja**
Summary

Closes #2486 

Changes

Added "go run ./cmd/ttn-lw-stack start" in the newly created "Starting The Things Stack" section

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md`. The target branch is set to `master` if the changes are fully compatible with existing API, database, configuration and CLI.
- [ ] Testing: The changes are covered with unit tests. The changes are tested manually as well.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by htdvisser** [comment]
It looks like your "prettier" plugin is formatting on save, so you should probably disable that (at least for markdown files).

**Comment by johanstokking** [comment]
Also check that the email address of your git config is in your GitHub profile

**Comment by jatinssaluja** [comment]
> It looks like your "prettier" plugin is formatting on save, so you should probably disable that (at least for markdown files).

I disabled it and it worked. Thanks. This also needs a mention in our documentation as it could lead to waste of time and efforts.

**Comment by jatinssaluja** [comment]
> Also check that the email address of your git config is in your GitHub profile

I just added it. Thanks.

**Comment by johanstokking** [comment]
1. Check the boxes where applicable in the PR template
2. Re-request review when ready

**Pull request merged**
