### PR TITLE
Fix release actions

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This is a quick fix for the release workflows.

#### Changes

- Trigger "Release Tag" workflow on rc tags
- Move documentation environment to the documentation job

#### Testing

Trial and error I guess

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]
No idea about the env but it's probably for a good reason

**Comment by htdvisser** [comment]
The env was previously only on the jobs that didn't end up on GitHub pages (so basically ineffective)

**Review by rvolosatovs — COMMENTED** [review]
This is not how this is supposed to work - we have snapshot builds for RCs.
Why was this merged? What is the reasoning behind it?
I do not see any related discussion, issue reference or even a clear answer as to "why" this is done and what other alternatives were considered.

**Comment by htdvisser** [comment]
We build snapshots from "master" builds, which is currently on every commit to the `v3.9` branch.

Release candidates should be exactly like actual releases, except that they're shown as pre-releases on GitHub. Release candidates are intended to test everything, including GitHub Pages, which isn't built by the Snapshot workflow (and didn't actually work, as it turned out).

**Comment by rvolosatovs** [comment]
Next time you have different opinions about how something should work, please voice them during review and not just suddenly decide to change things without discussion.
We already discussed it in https://github.com/TheThingsNetwork/lorawan-stack/pull/2744#discussion_r443411860 and you approved it, which means you explicitly accepted this approach and I do not see a reason why you would suddenly completely ignore that decision.

**Pull request merged**
