### PR TITLE
Allow resending the contact info validation email in Console

### LINKED ISSUE #6498: Manually re-request email validation from the console
### Summary

Manually re-request email validation from the console.

### Current Situation

If users don't validate the email before it expires, it requires a non-trivial amount of steps to get this fixed.
We have this option in the CLI but users who want to just use the console don't have an option.

### Why do we need this? Who uses it, and when?

Allow users to manage this themselves so that admins/support don't need to get involved.

### Proposed Implementation

- If a user logs in via the console and their email is not verified, then there should be a button to re-request email validation.
- This uses the `RequestValidation` method of the `ContactInfoRegistry` service.
- I think this can be simple button.

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary

image

Closes #6498 

#### Changes

- Add store logic for `requestValidation`
- Add a button to the error screen of restricted users to enable resending the validation email
- Some related cleanup of authentication related errors

#### Testing

1. Configure the stack to require validated contact info `--is.user-registration.contact-info-validation.required`
2. Create a new user
3. Log into the console
4. Observe the new error page which includes a "Resend validation email" button
5. Click the button
6. It will likely say that an email has already been sent recently (as part of the registration)
7. Wait until the validation token expires (or delete it manually in the DB)
8. Click the button again
9. A success message appears and the email is sent again

#### Notes for Reviewers

I don't really like that you can only resend the email when the old token is not pending. If for whatever reason the first email got lost, there's no way for the user to trigger another email other than waiting until the token expires. cc @nicholaspcr 

cc @KrishnaIyer 

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Comment by KrishnaIyer** [comment]
Looks great. 

Is this `Frontend Error ID` something that's attached by default to all errors?

> I don't really like that you can only resend the email when the old token is not pending. If for whatever reason the first email got lost, there's no way for the user to trigger another email other than waiting until the token expires. cc @nicholaspcr

I can see the case for this. @nicholaspcr: Please also ensure that this RPC is properly rate-limited to prevent users from spamming TTS and TTS wasting email credits.

**Comment by nicholaspcr** [comment]
@KrishnaIyer not sure if the rate-limit is a good idea here, since it uses the routes as a key so instead of limiting the ability of an user to resend its email multiple times we are just limiting the amount of email we can send in a period of time.

I understand that the idea behind what @kschiffer mentioned but we are talking about an edge case which is highly unlikely to happen and we would be spammed by users who received the validation email but its on their spam section. 

Having said that, I do see the necessity of being able to resend the validation email since the TTL is specially large. 
I currently can see two options:
1. We could leave a much shorter TTL in `is.user-registration.contact-info-validation.token-ttl`, specially since I'm imagining that the standard flow is to check the email inbox right after creation so there isn't a need to have a 48 hours TTL. The user would still have to wait but we don't add anything in order to accommodate an edge case.
2. We could cache the validation and that would have a specific TTL, so while it is in the cache an user could request for it to be sent again X amount of times (X probably being a low number in order to avoid spam).

In order for us to not fill this PR I created an issue https://github.com/TheThingsNetwork/lorawan-stack/issues/6525

**Comment by KrishnaIyer** [comment]
> @KrishnaIyer not sure if the rate-limit is a good idea here, since it uses the routes as a key so instead of limiting the ability of an user to resend its email multiple times we are just limiting the amount of email we can send in a period of time.

I said we should rate-limit the RPC, not using the existing rate limiting code. If our current rate-limiting logic doesn't work then we figure something else out. We can think of a max limit of retries per email ID or something. The point is that we don't want bots continuously triggering emails.

**Comment by kschiffer** [comment]
> Is this `Frontend Error ID` something that's attached by default to all errors?

It is an optional argument we can use in the frontend when defining errors. I just updated the errors to include these error codes which should make it easier for us to identify exact errors in screenshots but also on Sentry.

**Comment by KrishnaIyer** [comment]
Ok I see. Is there any reason why the user should see this? Can we hide this also in the "Technical details" section and ask users to expand that for screenshots if necessary?

**Comment by kschiffer** [comment]
I guess we could but I wouldn't want to modify that in this PR and I also don't think we should bother too much. It's really just there as a last resort to give some identifying info about the root cause when people are screenshotting errors.

**Comment by KrishnaIyer** [comment]
Yes right, I don't mean it should be in this PR. I think it's visually better to tuck this message in with the extra details.

**Comment by mjamescompton** [comment]
When error message is shown, the dropdown has the profile setting link. clicking this link will open the account app but will the page fails to load 

Screenshot 2023-09-14 at 14 30 36
Screenshot 2023-09-14 at 14 30 52

**Comment by mjamescompton** [comment]
@kschiffer you may want to add `Resend validation email` to the Japanese translations

**Review by mjamescompton — APPROVED** [review]

**Comment by kschiffer** [comment]
> When error message is shown, the dropdown has the profile setting link. clicking this link will open the account app but will the page fails to load
> 
> Screenshot 2023-09-14 at 14 30 36 Screenshot 2023-09-14 at 14 30 52

Indeed, this is currently broken but it's a separate issue, so let's resolve this in a separate PR. @ryaplots can you maybe look into that when you're back? We'd need to add a similar logic that checks the contact info validation in the Account App.

**Pull request merged**
